### ISSUE TITLE
Alternative Credentials for TFS On Premise

### ISSUE THREAD

**Issue by Quantumplation** [Microsoft/vso-agent#10]
Hello!

We are trying to preview this build agent, for use with our On Premise installation of Team Foundation Server 2015 RC.  It seems to rely on the VSO feature for "Alternative Credentials", but this tab is not available from the "Profile" dialog in TFS On Premise.  Is there something we need to do to enable this, or some other work around?

Regards,
Pi Lanningham

**Comment by 8106040** [comment]
hello!

The same issue I am facing for TFS 2015 RC. I always got 401 Unauthorized error when I created for an on premise agent. how can I proceed?

Thanks,
Hao Xu

**Comment by bryanmacfarlane** [comment]
We haven't written up instructions on xplat to on-prem.  But in short, you need to enable basic auth in IIS and use your credentials.  To ensure your credentials are not going over in base64 clear text, you'll want to configure https in IIS as well.

This guy did it here:  http://blogs.teamfoundation.co.za/2015/05/installing-and-configuring-tfs-2015-on.html 

I'll try and get formal docs on this at some point.

**Comment by Quantumplation** [comment]
Thanks for the reply!  I love everything I've seen out of the TFS and VSO teams lately!  Keep up the good work! :)

**Comment by 8106040** [comment]
Thanks for your comments,

but I am using IIS8, seems it do not have basic authentication, may I use Forms authentication or Windows authentication?

Br,
Hao xu

**Comment by bryanmacfarlane** [comment]
It does.  You may have to go into add/remove for windows to ensure that feature is enabled

Sent from Outlook<http://taps.io/outlookmobile>




On Fri, May 8, 2015 at 9:04 AM -0700, "8106040" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your comments,

but I am using IIS8, seems it do not have basic authentication, may I use Forms authentication or Windows authentication?

Br,
Hao xu

-

**Comment by bryanmacfarlane** [comment]
@Br 

How to install & enable basic auth in IIS8...  Be aware you need to install it as a feature and only then can it be enabled in IIS mgr

http://serverfault.com/questions/474882/how-do-i-enable-basic-authentication-for-iis-8-in-windows-server-2012

http://blogs.msdn.com/b/david_burgs_blog/archive/2013/11/05/installing-adding-iis-windows-authentication-feature-in-windows-8.aspx

**Comment by 8106040** [comment]
@bryanmacfarlane 
Thank you very much! Very helpful.

Regards,
Hao Xu

**Comment by ThomasKue** [comment]
I have an issue, whats going wrong here:
kind regards
Thomas

xxxxxxx@install-deb8:~/myagent$ node agent/vsoagent
Enter alternate username > xxxxxxx@DOMAIN.local
Enter alternate password >
successful connect as undefined
Retrieved agent pool: default (1)
install-deb8
2015-06-11T07:43:46.886Z: Agent Started.
##[Error] 2015-06-11T07:43:46.980Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2015-06-11T07:43:46.980Z: Failed Request: Forbidden(403) - http://tfs2015rc.DOMAIN.local:8080/tfs/_apis/distributedtask/pools/1/sessions
##[Error] 2015-06-11T07:44:01.990Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2015-06-11T07:44:01.990Z: Failed Request: Forbidden(403) - http://tfs2015rc.DOMAIN.local:8080/tfs/_apis/distributedtask/pools/1/sessions
##[Error] 2015-06-11T07:44:17.013Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2015-06-11T07:44:17.013Z: Failed Request: Forbidden(403) - http://tfs2015rc.DOMAIN.local:8080/tfs/_apis/distributedtask/pools/1/sessions
##[Error] 2015-06-11T07:44:32.025Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2015-06-11T07:44:32.025Z: Failed Request: Forbidden(403) - http://tfs2015rc.DOMAIN.local:8080/tfs/_apis/distributedtask/pools/1/sessions

**Comment by bryanmacfarlane** [comment]
@ThomasKue - see the instructions on the main readme.md.  You have to add the account to the AgentPoolServiceAccounts.  There's also a link to a video on configuring.

hth

**Comment by ThomasKue** [comment]
I read your instruction and I had created two accounts before.

Did you have any suggestion?

Regards
Thomas


Von: Bryan MacFarlane [mailto:notifications@github.com]
Gesendet: Donnerstag, 11. Juni 2015 12:40
An: Microsoft/vso-agent
Cc: Thomas Küssner
Betreff: Re: [vso-agent] Alternative Credentials for TFS On Premise (#10) [bayes][faked-from]


@ThomasKue<https://github.com/ThomasKue> - see the instructions on the main readme.md. You have to add the account to the AgentPoolServiceAccounts. There's also a link to a video on configuring.

hth

-

**Comment by bryanmacfarlane** [comment]
whichever account you're using when starting the agent, that account needs to be in that group

**Comment by ThomasKue** [comment]
Thanks for the clarification, now the agent started.

But now, I get this:
******************************************************************************
 Preparing tasks
******************************************************************************
******************************************************************************
 Running prepareWorkspace
******************************************************************************
preparing Workspace
cwd: /home/XXXXXXX/myagent/_work/build/573660dfef5a6fd833ad7433f6934387b698f979dd7311701c49868c971c8e55
##[Error] Unsupported repository type:TfsVersionControl


Please be so kind and tell me, whats going wrong.

Regards
Thomas



Von: Bryan MacFarlane [mailto:notifications@github.com] 
Gesendet: Donnerstag, 11. Juni 2015 14:30
An: Microsoft/vso-agent
Cc: Thomas Küssner
Betreff: Re: [vso-agent] Alternative Credentials for TFS On Premise (#10) [faked-from]

whichever account you're using when starting the agent, that account needs to be in that group
-

**Comment by bryanmacfarlane** [comment]
@ Thomas - TfsVC support for xplat is in a pull request right now.  We're going over it.  Should be in soon.  Works with git right now.

Can you do me a favor and create an issue for "403 Access denies" with your output and another for TfsVC support?  That will allow others hitting those to scan the issues and find the solution easily.

Thanks

**Comment by bryanmacfarlane** [comment]
Closing this issue since the on prem portion was answered
