### ISSUE TITLE
svc.sh install agent will fail if LaunchAgents folder does not exist

### ISSUE THREAD

**Issue by mcbuildmsft** [Microsoft/vso-agent#100]
After installing on a clean machine, attempting to install as a launch agent will fail if the LaunchAgents folder does not exist yet.

**Comment by bryanmacfarlane** [comment]
As it should.  It's not the agents job to fix OSX if a core systems folder is missing.

**Comment by bryanmacfarlane** [comment]
Do you have local install or one of the cloud hosting mac services?  I've seen/heard of bugs/issues in both that led to broken OSX
