### ISSUE TITLE
Add NTLM support in Agent

### ISSUE THREAD

**Issue by NikolayKash** [Microsoft/vso-agent#101]
Hello. 
There is a nodejs library which allows to connect to server side using ntlm auth https://github.com/SamDecrock/node-http-ntlm

We have the issue related to linux agent connecting to TFS 2015 on prem and we have to change auth mode in IIS http://blogs.teamfoundation.co.za/2015/05/installing-and-configuring-tfs-2015-on.html 

But this is not good from security perspective.

Is it possible to add NTLM support to Agent? 

Thanks!

**Comment by bryanmacfarlane** [comment]
Yes, I did a prototype using that exact library and it seems to work.  This is on the backlog and will hopefully come soon.  We also need it for tfx-cli

**Comment by NikolayKash** [comment]
Thanks to fast reply 
Can I get sources of your propotype?  
I can help with testing of it.

**Comment by bryanmacfarlane** [comment]
It was just a file that called [the http file in node-http-ntlm](https://github.com/SamDecrock/node-http-ntlm/blob/master/httpntlm.js) passing one of our intranet sites and it worked.

I will update this issue when we have something to try/test

**Comment by NikolayKash** [comment]
Ok, looking forward to get an update

**Comment by bryanmacfarlane** [comment]
Next month we start convergence on ONE core CLR xplat agent as opposed to a win agent and xplat node agent.  With that work will come ntlm support.  Closing this to backlog.
