### ISSUE TITLE
On-prem failed request during configuration

### ISSUE THREAD

**Issue by zwing99** [Microsoft/vso-agent#103]
when starting the agent all appears fine and then i get and it gets all the env variables and then i get a 500 error.

output:
Enter alternate username > myuser@MYDOMAIN.COM
Enter alternate password >
Enter server url > http://tfs.mydomain.com:8080/tfs
Enter agent name (enter sets lx-server)  >
Enter agent pool name (enter sets default)  > test
successful connect as undefined
Retrieved agent pool: test (2)
...................................... /// bunch of env vars
Error starting the agent
Failed Request: Internal Server Error(500) - http://tfs.mydomain.com:8080/tfs/_apis/distributedtask/pools/2/agents

Shutting down host.

**Comment by bryanmacfarlane** [comment]
Everything configured per docs here?

https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md

**Comment by gtritto** [comment]
Same error !

gtritto@gtritto-ubuntu:~/myagent$ node agent/vsoagent.js 
Enter alternate username > TFS\Administrator
Enter alternate password > 
Enter server url > http://tfsserver.tfs.local:8080/tfs
Enter agent name (enter sets gtritto-ubuntu)  > 
Enter agent pool name (enter sets default)  > linux
successful connect as undefined
Retrieved agent pool: linux (2)
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_VTNR=7
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SESSION_ID=c2
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap CLUTTER_IM_MODULE=xim
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/gtritto
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap COMP_WORDBREAKS= 	
"'><;|&(:
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap SESSION=ubuntu
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GPG_AGENT_INFO=/run/user/1000/keyring/gpg:0:1
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap SHELL=/bin/bash
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap VTE_VERSION=3803
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap WINDOWID=54525963
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/3142
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GNOME_KEYRING_CONTROL=
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GTK_MODULES=overlay-scrollbar:unity-gtk-module
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap NO_PROXY=localhost,127.0.0.0/8,::1
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap USER=gtritto
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap PATH=/home/gtritto/.kre/packages/KRE-Mono.1.0.0-beta1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap DESKTOP_SESSION=ubuntu
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap QT_IM_MODULE=ibus
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap QT_QPA_PLATFORMTHEME=appmenu-qt5
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SESSION_TYPE=x11
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap JOB=unity-settings-daemon
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap PWD=/home/gtritto/myagent
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XMODIFIERS=@im=ibus
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GNOME_KEYRING_PID=
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap LANG=it_IT.UTF-8
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GDM_LANG=it
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap IM_CONFIG_PHASE=1
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap COMPIZ_CONFIG_PROFILE=ubuntu
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GDMSESSION=ubuntu
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap SESSIONTYPE=gnome-session
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SEAT=seat0
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap HOME=/home/gtritto
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap LANGUAGE=it
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GNOME_DESKTOP_SESSION_ID=this-is-deprecated
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap no_proxy=localhost,127.0.0.0/8,::1
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap UPSTART_INSTANCE=
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap UPSTART_EVENTS=xsession started
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_SESSION_DESKTOP=ubuntu
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap LOGNAME=gtritto
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap COMPIZ_BIN_PATH=/usr/bin/
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap QT4_IM_MODULE=xim
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-SwA4DV3hv4
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap LESSOPEN=| /usr/bin/lesspipe %s
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap INSTANCE=
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap UPSTART_JOB=unity7
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_RUNTIME_DIR=/run/user/1000
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap DISPLAY=:0
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XDG_CURRENT_DESKTOP=Unity
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap GTK_IM_MODULE=ibus
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap LESSCLOSE=/usr/bin/lesspipe %s %s
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap XAUTHORITY=/home/gtritto/.Xauthority
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap _=/usr/bin/node
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap OLDPWD=/home/gtritto
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : PATH=/home/gtritto/.kre/packages/KRE-Mono.1.0.0-beta1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap ant=/usr/bin/ant
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap clang not found
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap cmake not found
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap curl=/usr/bin/curl
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap git=/usr/bin/git
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap jake=.
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap java=/usr/bin/java
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap make=/usr/bin/make
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap Xamarin.iOS=/usr/bin/mdtool
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap mvn not found
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap node.js=/usr/bin/node
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap node.js=/usr/bin/nodejs
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap npm=/usr/bin/npm
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap gulp not found
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap python=/usr/bin/python
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap python3=/usr/bin/python3
Tue Oct 27 2015 19:59:46 GMT+0100 (CET) : cap sh=/bin/sh
gtritto-ubuntu
Error starting the agent
Failed Request: Internal Server Error(500) - http://tfsserver.tfs.local:8080/tfs/_apis/distributedtask/pools/2/agents

Shutting down host.

**Comment by gtritto** [comment]
To receive this error i  enabled basic authentication.
It seems a vsoagent problem, because if from my ubuntu I try to navigate with firefox on http://tfsserver.tfs.local:8080/tfs/_apis/distributedtask/pools/2/agents , after credential request, TFS gives me a json list of task.

So my opinion is that vsoagent need to improve the connection session process.

I wanna try to prepare my ubuntu to debug vsoagent.js.
Can Any one  give me some instructions to use eclipse 3.8 to debug vsoagent.js ?

thanks 

gtritto

**Comment by bryanmacfarlane** [comment]
This is a service side issue and it's likely a bug with something in the capabilities payload (something not getting escaped etc... in what you see dumped to screen.

Here's how to see what comes over the wire and the response from the service.  Use charles http proxy.

https://www.youtube.com/watch?v=PAVG50t_1bw

**Comment by bryanmacfarlane** [comment]
Improved for on-prem.  Docs updated.

Note you have to use the @preview version and during configuration set force basic to true
