### ISSUE TITLE
Support running as a service on Linux

### ISSUE THREAD

**Issue by drolevar** [Microsoft/vso-agent#105]
For the time being Linux.js service installer is absent form the svcinstall project, which makes it impossible to install a service on Linux.
If there's anything (pre-alpha :)) ) available, would be glad to test it.

**Comment by kkirby** [comment]
I think the bigger problem is that vso-agent isn't capable of demonizing itself.

**Comment by bryanmacfarlane** [comment]
Docker is the way we're going to support running Linux

**Comment by drolevar** [comment]
Could you provide some details about how it's going to be implemented?
Currently during the initial phase we start it using screen, but that's
obviously not the way to go.
20 окт. 2015 г. 21:01 пользователь "Bryan MacFarlane" <
notifications@github.com> написал:

**Comment by bryanmacfarlane** [comment]
Soon ... TFS QU1 release delayed this work

**Comment by mvucinic** [comment]
can running as a background service can be achieved using pm2 or similar tools?
current problem running it with pm2 is additional params I need to add when starting the service: alternate name and password...can these be hardcoded?

**Comment by bryanmacfarlane** [comment]
-u {username} -p {password}

**Comment by bryanmacfarlane** [comment]
... there is another story to support cred stores

**Comment by mvucinic** [comment]
That worked!

Thank you

MARKO VUCINIC
Consultant

Tel.: 416-649-3690 ext. 249 | Cell: 647-532-8891 | Email: mvucinic@objectsharp.com
<mailto:mvucinic@objectsharp.com>Twitter: @TeamObjectSharp<https://twitter.com/TeamObjectSharp> | Blog: blogs.objectsharp.com
<http://blogs.objectsharp.com/>Office: 40 University, # 1301, Toronto, ON M5J 1T1 | www.objectsharp.com<http://www.objectsharp.com/>

**Comment by kp2015** [comment]
Does this still work with the ./run.sh ?

I'm trying but not having any luck.

**Comment by bryanmacfarlane** [comment]
run.sh is just a wrapper so you can still call host or vsoagent with -u -p.  I'll change run.sh today to pass those args along.

**Comment by kp2015** [comment]
so i should be able to do this: $ ./runtime/node/bin/node agent/vsoagent.js -u <username> -p <password> ?

**Comment by kp2015** [comment]
Figured out my issue here as well. Was necessary to add quotes around the username and password.

**Comment by bryanmacfarlane** [comment]
The replacement for this agent supports running as a service on linux. We are releasing a new preview tomorrow or early next week. It already has more features than this one

https://github.com/Microsoft/vsts-agent

**Comment by smecsia** [comment]
For those, who is still looking for the easy way to launch build agent under linux as a service. We've solved this problem by hard coding the credentials in `agent/common.js`: 

```javascript
function getCreds(done) {
    var creds = {};
    creds['username'] = 'USERNAME';
    creds['password'] = 'PASSWORD';
    done(err, creds);
}
```

```javascript
function readBasicCreds() {
    var defer = Q.defer();
    var credInputs = [
        {
            name: 'username', description: 'alternate username', arg: 'u', type: 'string', req: true
        },
        {
            name: 'password', description: 'alternate password', arg: 'p', type: 'password', req: true
        }
    ];
    var cred = {};
    cred.username = 'USERNAME';
    cred.password = 'PASSWORD';
    defer.resolve(cred);
    return defer.promise;
}
```

After this all you need to do is to launch `agent.sh` file with `pm2` daemon launcher:
```
$ pm2 start agent/vsoagent.js
```

**Comment by bryanmacfarlane** [comment]
pm2 is fine.

A better option would be to pick up the agent that's replacing this one and already has more capabilities (including run as a systemd service on Linux)

https://github.com/Microsoft/vsts-agent
https://github.com/Microsoft/vsts-agent/releases

**Comment by bryanmacfarlane** [comment]
And if you use pm2, no need to hardcode creds.  vsoagent.js takes -u and -p cmdline args

**Comment by smecsia** [comment]
@bryanmacfarlane Thanks. When we used vsoagent.js first time, it didn't take these arguments. We'll try the new version then.
