### ISSUE TITLE
When can we use build vNext on VSO?

### ISSUE THREAD

**Issue by paulsapps** [Microsoft/vso-agent#11]
Question as per title - I'd like to use an azure VM as my build agent for VSO! :+1:

**Comment by bryanmacfarlane** [comment]
I have azure VMs running build agents today.

Is the question when can I install an agent on an azure VM?  or..
Is the question when is the hosted pool going to be available for build.vnext? (don't need to get your own VM)?

If it's the former, the answer is today.  If it's the latter, the answer is a week or two.  

However, note that this xplat agent is for OSX | Linux.  The hosted pool is windows machine.  For linux, you can bring your own azure vm and follow the instructions on this repo.  For OSX you have to bring your own and follow instructions on this repo.  For example, I have a cloud mac at macstadium and run automated builds and tests for this agent.

**Comment by paulsapps** [comment]
If I install a build Agent today on an Azure VM my Visual Studio Online account UI has no build vNext option? So I was wondering when this part was going to appear since I can't use the agent without it?

**Comment by bryanmacfarlane** [comment]
OK - the updates to turn it on are just now starting to roll out to the scale units.  So it might be as early as days away but no more than a week or so away

**Comment by paulsapps** [comment]
Thanks I'll keep an eye on it, its still not there yet :hushed:

**Comment by chrisrpatterson** [comment]
The new build system and hosted pool are available to all accounts.
