### ISSUE TITLE
Environment variables not set

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#112]
I have a android solution that has a prebuild event. It's an exe files that generates some code. This is the prebuild event as it appears in visual studio.
"$(SolutionDir)packages\refit.2.3.0\tools\InterfaceStubGenerator.exe" "$(ProjectDir)RefitStubs.cs" "@(Compile)"
This works when building in xamarin studio or visual studio.

When queuing a build the prebuild event attempts to run but errors out
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1249,5): Error MSB3073: The command ""*Undefined*packages\refit.2.3.0\tools\InterfaceStubGenerator.exe"
As you can see $(SolutionDir) is not set on comes through as *Undefined*. Is there anyway you can get $(SolutionDir) to be populated automatically with the correct path?

Upon further investigation I created a variable in the build called SolutionDir and gave it this value $(Agent.BuildDirectory)\s\Mobile\. This should have been the correct path but the build failed again producing this: C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1249,5): Error MSB3073: The command ""$(Agent.BuildDirectory)\s\Mobile\packages\refit.2.3.0\tools\InterfaceStubGenerator.exe". As you can see $(Agent.BuildDirectory) did not get mapped to the proper location. 

After hard coding the path in my SolutionDir variable on the build to C:/agent... was I able to get the build to succeed. This is highly undesirable as there could be multiple build agents in different paths and this would only work for one.

After I got the build to succeed I attempted to sign the result apk. I got an error saying JAVA_HOME was not correct. I attempted setting this as a system variable on my computer with no luck. I was forced to make a build variable called JAVA_HOME and give the absolute path for java. This is highly undesirable again because what I have I have 2 build agents on different machines with different java versions? These variables need to be agent specific not build specific.

**Comment by bryanmacfarlane** [comment]
When we configure the agent, if you're running as an OSX service, we dump a .env file in the root of the agent.  When it starts we read and set those envvars.  

So:
- Was JAVA_HOME set at the time you configured the agent as a service?  If so, check .env file
- If not, edit the .env file and restart.

We should probably document ...
