### ISSUE TITLE
Vso agent won't get lastest because of already mapped workspace

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#114]
Getting this error on the preview version
An error occurred: The path /myagent/_work/1/s is already mapped in workspace ws_1_10.
rc:100
success:false
/usr/bin/tf failed with return code: 100

**Comment by yacaovsnc** [comment]
@rusty21 Did you install a new agent on the same path of some old agent instances at /myagent?  Each agent instance has an agent id, and we use the agent id in the workspace name to avoid collisions.  If you install a new agent on the same path, you could get this error.

**Comment by rusty21** [comment]
Seems to have fixed that particular problem.
