### ISSUE TITLE
Issue with Xplt agent on Linux with DEployment task for Tomcat

### ISSUE THREAD

**Issue by scantini** [Microsoft/vso-agent#116]
Hi 
I am using the xplat agent for Linux (v1.999.0) with npm agent version : 0.3.4.
I am using in my release definition the "tomcat deployment" task. When starting a release, I have the following error message : 
2015-10-14T10:31:10.921Z: Running job: Release
2015-10-14T10:31:11.037Z: Job Completed: Release
##[Error] 2015-10-14T10:31:11.045Z: Error: Agent could not find a handler for this task
2015-10-14T10:31:12.448Z: Job Finished: Release

When using the Windows Agent, it is working fine.
Regards
Sébastien.

**Comment by bryanmacfarlane** [comment]
The issue isn't with the agent.  the issue is that the task is written for windows only.

Log the issue in this repo

https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/TomcatDeployment
