### ISSUE TITLE
Service not functioning, no feedback

### ISSUE THREAD

**Issue by ColinDabritzViewpoint** [Microsoft/vso-agent#118]
Thanks for this toolkit, we're working on a Xamarin iOS build via VSO and this is keeping me going for now.

I am attempting to hook up my Mac build machine with Xamarin as a build agent on VSO. My issue is that running interactively works, and shows a green agent connection in VSO in the pool, but immediately following that by running the service with `$ sudo node service start` doesn't seem to work in VSO, the "light" stays red.

I'm getting no real feedback to understand what the status is, if the agent thinks it's connected or not, any errors, etc.

I'm also not sure where the configuration lives, but I'm assuming it is using the same configuration as the interactive mode. I'm not clear how this could be reset, other than deleting the directory and creating a new agent.

The command line gives me this:
> $ sudo node service start
> action: start
> serviceName: vsoagent.vsoagent.ourvsosite.mymachinename.fully.qualified
>  
> start /Library/LauncheDaemons/vsoagent.ourvsosite.mymachinename.fully.qualified.plist
> Success
>
> status vsoagent.ourvsosite.mymachinename.fully.qalified
> 1321    0    vsoagent.ourvsosite.mymachine.fully.qualified
> 
> Success

The status command repeats the status at the end.

How can I get more information about the state, what settings are being used, or why the service mode would be functioning differently?

Should the script give more information or feedback here?

Thanks much,
Colin

**Comment by bryanmacfarlane** [comment]
>> start /Library/LauncheDaemons/vsoagent.ourvsosite.mymachinename.fully.qualified.plist

We created the OSX plist for you per output as a convenience.  At this point, you can use our svc.sh script for a few convenience operations or you can use the OSX cmdline launchctl which is how you manage services.  That output (1321) also gives you the pid of what's running.

Further if you open the OSX utilities/console app we create logs per OSX standards.

Per the instructions here, you're also supposed to use svc.sh and it offers a status command

https://github.com/Microsoft/vso-agent/blob/master/docs/service.md 

I don't know what more information you're looking for and we're hesitant to create other tools and conventions outside the standard set of OSX service tools and logs.  Unfortunately for windows folks (Xamarin etc...) it means ramping up a bit on OSX OS and services :)

hth

**Comment by ColinDabritzViewpoint** [comment]
Those sound helpful, I can take a look. It sounds like it was mostly a matter of not being familiar with the tools!
