### ISSUE TITLE
Run Agent as Service err when run ./svn.sh install

### ISSUE THREAD

**Issue by haxu** [Microsoft/vso-agent#12]
hi there,

I get the following err when I install agent as service. could you help on this?
@ubuntuAgent:~/ubuntuAgent/agent$ ./svc.sh install
serviceName: vsoagent.vsoagent.192.ubuntuagent

module.js:340
    throw err;
          ^
Error: Cannot find module './installers/Linux'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at new SvcInstall (/home/haxu/ubuntuAgent/node_modules/svcinstall/lib/svcinstall.js:13:20)
    at Object.<anonymous> (/home/haxu/ubuntuAgent/agent/service.js:32:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Regards,
Hao Xu

**Comment by bryanmacfarlane** [comment]
Per instructions on the main page for running as a service: 
Run in the agent directory note: only works on OSX right now

On Linux you can run interactively, use nohup or use docker.

**Comment by bryanmacfarlane** [comment]
We will add Linux runs as a service or docker features in a future release.  Added to our backlog

**Comment by insanity13** [comment]
/*Run in the agent directory note: only works on OSX right now
Got the same error on OSX Yosemite

**Comment by bryanmacfarlane** [comment]
You got an error that it can't load the Linux installer on OSX?  Can you paste the output?

**Comment by insanity13** [comment]
![output](https://cloud.githubusercontent.com/assets/1174911/10795819/ee511e24-7db4-11e5-90cb-3e96c2809785.PNG)

**Comment by bryanmacfarlane** [comment]
The instructions say to run svc.sh from the "agent" folder.  Looks like you're one above the agent folder? (I think someone just did a PR to fix that).

But, it's not the same as Linux support which is what this issue is tracking

**Comment by insanity13** [comment]
/*Looks like you're one above the agent folder? 
Got that, thanks. But it's really strange to write in instructions "./agent/svc.sh install"
But in other cases "agent directory" is the folder where VSO was installed.

**Comment by insanity13** [comment]
Now got this.
![output](https://cloud.githubusercontent.com/assets/1174911/10798904/566839ee-7dc3-11e5-8438-23ce52951e99.PNG)

**Comment by bryanmacfarlane** [comment]
We're basically generating an OSX plist file and running chown on it.  Does the LaunchAgent path outputted exist?

**Comment by insanity13** [comment]
I've created "LaunchAgents" manually, and it's worked. Thanks a lot!

**Comment by bryanmacfarlane** [comment]
That's interesting - it's an OSX system folder.  I've seen folks have it missing and remember seeing an apple bug where's it's sometimes not there.  odd

**Comment by prawalagarwal** [comment]
Hi Bryan,  

Is support for Running agent as service on Linux enabled now? I still see the Cannot find module error.

**Comment by bryanmacfarlane** [comment]
It has always been supported.  Just create an initd, systemd file.  We just don't create it for you as a convenience like OS X.  An units is just a shell script so go for it

If you want to do it today without creating a script j would also recommend looking at pm2.  It's easy to install and will keep it running

Someone is looking at Linux scripts right now

**Comment by grawcho** [comment]
is there an ETA on the "Run linux agent as a service" Feature?
