### ISSUE TITLE
Curl script https not supported or disabled in libcurl

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#122]
Attempting to use a curl script to upload a file to a remote location. It caused this error curl: (1) Protocol "https" not supported or disabled in libcurl. Using http is not an option. I assume that libcurl is somehow included with the agent when its installed. Can a version that supports https be included?

**Comment by bryanmacfarlane** [comment]
The agent doesn't distribute libcurl - it's written in javascript.  Issue is not with agent ...
