### ISSUE TITLE
With TFS 2015 Update 1 RC1 can no longer connect vsoagent to CentOS 64-bit Linux boxes.  Bad Request Received

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vso-agent#123]
Failed Request: Bad Request(400) - http://machinename:8080/tfs/_apis/distributedtask/pools/6/agents

**Comment by bbusacker** [comment]
I have to run my 32-bit Linux build elevated so I set the VSO_AGENT_RUNASROOT in the environment.  Once I do that this error message goes away but it does not go away for 64-bit CentOS6 or CentOS7.

Is there a way to not run the agent as root on Linux?   

This same issue exists on the release as well as preview version of the agent.

I'm using 

node: 0.12.2
npm: 2.7.4

**Comment by bryanmacfarlane** [comment]
What version of the agent are you using?
Have you tried to reconfigure the agent (there was a known issue in RC1 where you had to reconfigure the agent).  It led to a session conflict which I believe is a 400.

Running as root shouldn't matter but perhaps the act of setting up the agent to run as root got rid of the session conflict.

Can you try to setup a new agent as non root? (they can exist SxS on same machine, just different folder, different name of agent).  It should work

**Comment by bbusacker** [comment]
Complete blew away my original agent folders and installed new ones.  Appears it may be an something in the environment that is causing the issue.   PATH variable too long or something.  Haven't narrowed it down. yet.  Any suggestions on how to get at the root cause of this issue?

**Comment by mpeder** [comment]
I am seeing the same issue with Ubuntu and Mac OS...

**Comment by chrisrpatterson** [comment]
I think this is related to a bug in the agent where it is not showing you the error message from the server.  There have been some changes in the purchasing model for build in VSO where you only get 1 private agent for your account for free and have to purchase additional agents.  You can read more here https://www.visualstudio.com/en-us/get-started/setup/get-more-build-or-load-testing-vs.

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson - but I think this is on-prem QU1.  It's more likely to be the QU1 CTP1 issue where you have to reconfigure the agent which is in the readme.

@mpeder - can you reconfigure an agent (delete the existing one from the web UI) and delete the .agent file?

**Comment by mpeder** [comment]
@chrisrpatterson You were right as soon as I deleted the other agent I had running I was able to install the new one on Linux :-)

**Comment by bryanmacfarlane** [comment]
@mpeder - are you connecting to on-prem TFS?
