### ISSUE TITLE
Using vso-agent to handle pre PR-complete builds doesn't work

### ISSUE THREAD

**Issue by ryanmolden** [Microsoft/vso-agent#124]
If you configure your VSO repo branch policy to require a build before a PR can be completed, if that build occurs on an agent running vso-agent it fails complaining the given id is not a tree.

Repro steps:

1: Set up build machine running Mac/Linux
2: Install agent, join to build pool
3: Set repo policy to invoke build definition targeted at agent from step #2 before PR completion
4: Submit a PR to the repo

Expected: The build to run, and assuming the PR changes are valid, to pass

Actual: Fails on repo sync step trying to sync to an id (it was given) that it complains is not a valid tree.

**Comment by bryanmacfarlane** [comment]
Scott is fixing

**Comment by bryanmacfarlane** [comment]
This is address in 0.3.5 preview agent.  Main readme has instructions on installing preview.  Will get promoted to released soon.
