### ISSUE TITLE
Build - Source directory needs to be consistent for Local Agent vs. VSO ages.

### ISSUE THREAD

**Issue by cicorias** [Microsoft/vso-agent#128]
Running a build with the Agent (local) uses 'build.sourcedirectory (note the singularity of 'source) vs. in VSO, lt's 'build.sourcesdirectory.

Be nice if it was consistent.

**Comment by bryanmacfarlane** [comment]
This should be address in 0.3.x preview.  Have you tried that one?

**Comment by cicorias** [comment]
well, can't see the source for that, nor is it up on npm. So, no.

**Comment by bryanmacfarlane** [comment]
0.3.x is in npm.  Instructions are at the bottom of the readme on the front page of this repo. 0.3.x is out of master

**Comment by cicorias** [comment]
Actually, just tried ```npm install vsoagent-installer@preview --save```

And still broke: 
```
    WellKnownVariables.sourceFolder = "build.sourceDirectory";
    WellKnownVariables.stagingFolder = "build.stagingdirectory";
```

So, the PR still makes sense.

**Comment by cicorias** [comment]
update PR to use the context.ts vars. see #129

**Comment by bryanmacfarlane** [comment]
this was fixed
