### ISSUE TITLE
On-prem TFS / OSX Build. Run as a daemon failed with 401or 403

### ISSUE THREAD

**Issue by insanity13** [Microsoft/vso-agent#136]
When agent start interactively it work fine. 
But when I try to start it as daemon it fails with 401.
stdout.log shows that env vars set right.
How to set authentification for deamon correctly?
I'm could not find anything in docs.

**Comment by bryanmacfarlane** [comment]
Can you add details on how you ran it as a daemon.  Do you mean a launch daemon?  Can you provide other details?  Are you connecting to an on-prem server?

**Comment by insanity13** [comment]
Sorry for a long silence.
Yes, it's a on-premise server.
Today update agent to 0.3.13 but it does not helps.

![output](https://cloud.githubusercontent.com/assets/1174911/11506276/19d2f95a-9868-11e5-8d63-a715833b129c.PNG)

![output2](https://cloud.githubusercontent.com/assets/1174911/11506418/e85a94cc-9868-11e5-8f78-5056e84ceaac.PNG)

**Comment by insanity13** [comment]
Any ideas?

**Comment by bryanmacfarlane** [comment]
check out the read me for updated instructions for on-premise (use preview version).

However that's not what you're hitting.  401 means bad creds.

So, first, let's interactive (not daemon).  Does that work?
Second, look in the plist that's referenced.  What creds are in it?

**Comment by insanity13** [comment]
/*So, first, let's interactive (not daemon). Does that work?*/
Yes, I've said it in my previous message.

**Comment by bryanmacfarlane** [comment]
>> Second, look in the plist that's referenced. What creds are in it? 

I wonder if it's a quoting/escaping issue in that file?? Also, you will need to append the flag to force basic (let me look that up).  Just realized that will be needed.

**Comment by insanity13** [comment]
So I've updated agent to "0.4" version, node to 4.2.3
Removes old agent, reconfigure, set force-basic, and now got 403 at interactive mode:
![403](https://cloud.githubusercontent.com/assets/1174911/11710037/b730a836-9f35-11e5-9e9e-65e70109ad27.PNG)

this user in "Agent Pool Service Account" and "Agent Pool Administrators"

**Comment by insanity13** [comment]
Got it! Added user to "Project Collection Service" group.

**Comment by insanity13** [comment]
Daemon still fails
![401](https://cloud.githubusercontent.com/assets/1174911/11710542/5cac811a-9f39-11e5-8f02-5a2146752efb.PNG)

**Comment by bryanmacfarlane** [comment]
adding scott

Just to confirm, you got it to work interactively by adding to the Project Collection Service group (we should figure out why - wasn't expecting).

But, you're still having an issue with the service?  (note the plist is just telling it to run what you did interactively).  Try interactively with -u and -p args (what the plist does)

**Comment by insanity13** [comment]
![401_2](https://cloud.githubusercontent.com/assets/1174911/11715590/81c6af2a-9f5c-11e5-94c1-5199670a1366.PNG)
I've got a minus character in my password

**Comment by bryanmacfarlane** [comment]
Ha!

>> I wonder if it's a quoting/escaping issue in that file??

:) Looks like we need to fix that.

Does quoting it work?

**Comment by insanity13** [comment]
I've tried -u "user.name" -p "password", but it does not helps.

**Comment by bryanmacfarlane** [comment]
I updated the README.md to have specific on-prem instructions link.  There were additional permissions needed (now doc'd) and a couple of fixes.

I would recommend getting a new agent via the latest instructions
