### ISSUE TITLE
Question: Access TF OAuth token from custom build step

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#140]
I'm trying to write a custom build step that uses tf to check out a file modify it and check it back into source control. Whenever I try to check a file back in with my own credentials I always get an unauthorized error. Is there a way I can get access to the OAuth token that the agent uses to get latest on the code? If not, is there something else I can do so that I can check files in/out with out hard coding some username and password?

**Comment by bryanmacfarlane** [comment]
We have a story which should come in a sprint or two which has a checkbox to make the OAuth token available to ad-hoc scripts.

in the short term, the work around is to create a PAT token and put it in a secret variable on the definition

**Comment by rusty21** [comment]
That sounds great! I tried making a PAT but when trying to check the file back in I get this error. An error occurred: TF204017: The operation cannot be completed because the user does not have one or more required permissions (CheckIn) for workspace ws_1_22;Project Collection Build Service (mybuildservice)

**Comment by bryanmacfarlane** [comment]
The story is in.  There's a check box on the options tab of the build definition.  Check that and then run a script to see dump env.  You'll see the OAuth token is exposed to your build scripts if you check that.
