### ISSUE TITLE
Getting an error while running a task

### ISSUE THREAD

**Issue by vishnugms** [Microsoft/vso-agent#143]
I am getting following error while running HockeyApp task on x-plat agent - 

Error: 
Failed to extract zip:  /users/rmuser/Downloads/_package/vsoxplat/_work/tasks/HockeyApp/0.9.18.zip

Any clue why I am hitting this issue? Same task works well on windows agent.

**Comment by ankitgo** [comment]
This task is at collection level. When we make a call to download a task, from xplat agent, its at the account level. Maybe we should fix the task download logic here.

**Comment by bryanmacfarlane** [comment]
There’s a PR for that we need to get in.

**Comment by vishnugms** [comment]
Thanks Ankit and Bryan for letting me know. 
Bryan can u plz share the PR so that I can validate this app deployment?

**Comment by bryanmacfarlane** [comment]
Should be fixed in 0.3.13 and preview version of the agent
