### ISSUE TITLE
Using tsd to version definitions files

### ISSUE THREAD

**Issue by AbraaoAlves** [Microsoft/vso-agent#144]
Definitions files are updated manually and this is an opportunity for bugs.

ex:
'vso-node-api' is updated with changes in the interface, but its .d.ts files not copied to this repository.

Solution:
All definitions are versioned by [tsd.json] (https://github.com/DefinitelyTyped/tsd#tsdjson)

**Comment by bryanmacfarlane** [comment]
not going to do this since this agent is being replaced.

https://github.com/Microsoft/vsts-agent
