### ISSUE TITLE
vsoagent on Mac keeps giving  Error: Agent could not find a handler for this task.

### ISSUE THREAD

**Issue by sahino** [Microsoft/vso-agent#145]
Hi Everyone,

We're trying to setup a Xamarin IOS build pipe in Visual Studio Online based on VNext and the xplat vsoagent. The VSO agent has been installed and configured on a Mac based on instructions from git and our visual studio online environment has also been configured as described with a AgentPool etcetera.

I created a new build definition and added / configured several steps and everything seems fine.
 For some reason when I queue a build, the build fails and the agent on the Mac gives me the following error:
 Error: Agent could not find a handler for this task.

When I strip the Build definition down to 1 step (e.g. nuget package installer or the IOS Build Step, or the Xamarin License step) it still fails giving the message mentioned above.

Stuck for 2-3 days now, since no information regarding this specific issue can be found.

Any help would greatly be appreciated.

**Comment by bryanmacfarlane** [comment]
Adding Madhuri

**Comment by bryanmacfarlane** [comment]
What that error means is you are using a task that only has a powershell implementation (needs to run on windows).

Look through the tasks and specifically the xamarin license task 
https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks 

Notice in there's no task.js - just a ps1

You can activate the xamarin license on your mac manually.  You're not blocked.  The reason for the windows license task was to activate on the hosted build windows box where you don't have access to the machine

**Comment by sahino** [comment]
Ok, so far clear for me, thanks! Our solution uses nuget packages though. Before the xamarin build step in the build definition we do a nuget installer step to restore the packages before the build. This also results in a handler error. That would mean that the step also hasnt been implemented right? When I remove it, the xamarin ios build step fails due to being unable to restore the packages. Any ideas?

**Comment by madhurig** [comment]
The Xamarin.iOS task runs nuget restore on the solution file. Nuget restore works only at the solution level. If your solution has other platforms that can't be built on iOS then you should setup a configuration for iOS that will exclude building those but build the common libraries. You can then pass that configuration to the Xamarin.iOS task. 

Sorry for the delay and hope this helps.
-Madhuri

**Comment by appsandbeyond** [comment]
I get the same error when I configure the build definition to work with an iOS project only (no Android or Winwows Phone). So the NuGet installer step it's pointing to a iOS only solution file. It look like this has all to do with the pre-release status of the Cross Platform Build Agent.

**Comment by bryanmacfarlane** [comment]
Madhuri gave the explanation above.  Either way, not an agent issue.  If you're still having an issue with building Xamarin, it should be tracked in vso-agent-tasks repo where the xamarin task is
