### ISSUE TITLE
Step with "Always Run" does not run if previous step fails

### ISSUE THREAD

**Issue by JanMattner** [Microsoft/vso-agent#151]
Hi there,

I stumbled upon this error while trying to publish test results after running unit tests. If the "run tests"-step fails, the publish step should be executed nevertheless. The checkbox "Always Run" in the "Control Options" of the step should do the trick, but the step is not run if any step before it fails.

I tried it even with simple "Command Line" steps, but this does not work either, so it seems that it is not related to the step but rather to the vsoagent itself.

I tried it with vsoagent version 0.3.10 and 0.3.11. It runs on a Debian system and is triggered by an on-prem TFS 2015 (version 14.0.23128.0).

**Comment by atinb** [comment]
@JanMattner 
If you check the "Continue on Error" check box for the previous "run tests" task, this should work.
Thanks!

**Comment by JanMattner** [comment]
Thanks for the feedback. But actually no, this is not the desired behavior. With "continue on error", if the step fails, all following steps are executed and the overall build partially succeeds.

But I want that only specific following steps are executed and the build should really fail. Actually this is exactly how I have done it in a VSO project with the Powershell agent on a Windows machine in Azure.

So either my configuration or whatever is wrong or it is a bug of TFS on-prem or the vsoagent. But certainly "continue on error" is not the solution.

----- Ursprüngliche Nachricht -----
Von: "Atin Bansal" <notifications@github.com>
Gesendet: ‎17.‎11.‎2015 17:30
An: "Microsoft/vso-agent" <vso-agent@noreply.github.com>
Cc: "Jan Mattner" <jan.mattner@gmail.com>
Betreff: Re: [vso-agent] Step with "Always Run" does not run if previous stepfails (#151)

Closed #151.

**Comment by JanMattner** [comment]
@atinb 
Could you please open the issue again? It is _not_ resolved. Your solution is unfortunately not applicable in order to fulfill my requirements stated above.

**Comment by Lugribossk** [comment]
I reported a similar issue in the vs-agent-tasks project at https://github.com/Microsoft/vso-agent-tasks/issues/426

**Comment by JanMattner** [comment]
@Lugribossk 
Yes, that seems to be the same issue.
In the special case of publishing test results, the workaround that I do now is the following setup:

Run tests with Continue on error = true
Publish test results
Run tests with Continue on error = false

This way the build fails for failing tests but the results are properly published. The disadvantage here is of course that the tests are executed twice and thus the build takes more time.

**Comment by bryanmacfarlane** [comment]
This is addressed in the new agent that's replacing this.  It's going into preview this week:  https://github.com/microsoft/vsts-agent

**Comment by grawcho** [comment]
i committed a fix for this issue in my fork if you are interested.
