### ISSUE TITLE
Agent doesn't automatically fetch updated tags

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vso-agent#152]
Tags are supposed to be immutable. Situations do occur, though, in which we must update tags. The build agent never seems to fetch the updated tags. We had to manually connect to the agent and run `git fetch --tags`.

@joaomoreno

**Comment by bryanmacfarlane** [comment]
Can you log this issue in the new agent?  We'll make sure the new one handles this

https://github.com/Microsoft/vsts-agent

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vsts-agent#106
