### ISSUE TITLE
Agent keeps retrying on some 400 level errors

### ISSUE THREAD

**Issue by thechrisjohnson** [Microsoft/vso-agent#153]
The agent will loop continuously trying to listen for messages even after receiving different 400 level responses (e.g. remove view pool permission for account running agent, remove account running agent from Service Accounts group)

**Comment by bryanmacfarlane** [comment]
already fixed

https://github.com/Microsoft/vso-agent/commit/121e80133612275121659e1e908f8d2afa185a1d

**Comment by bryanmacfarlane** [comment]
or is this a diff req?

**Comment by thechrisjohnson** [comment]
Different issue. Commit that fixes has been merged.
