### ISSUE TITLE
Unable to run build agent due to EACCES error

### ISSUE THREAD

**Issue by miguelarcilla** [Microsoft/vso-agent#155]
I'm following the CI tutorials listed in the PartsUnlimitedMRP project, and am setting up my Linux Virtual Machine to be a build agent.

I have installed the necessary prerequisites and created a folder named "vstsbuild" in which I intend to run the `node agent/vsoagent` command. I am able to successfully log in, but when it tries to provision and start the build agent, I get the ff. error:

    Creating work folder ./_work ...
    shell.js: internal error
    Error: EACCES, permission denied './_work'
        at Error (native)
        at Object.fs.mkdirSync (fs.js:747:18)
        at mkdirSyncRecursive (/home/usr/vstsbuild/node_modules/shelljs/src/mkdir.js:11:8)
        at /home/usr/vstsbuild/node_modules/shelljs/src/mkdir.js:63:7
        at Array.forEach (native)
        at Object._mkdir (/home/usr/vstsbuild/node_modules/shelljs/src/mkdir.js:48:8)
        at Object.mkdir (/home/usr/vstsbuild/node_modules/shelljs/src/common.js:172:23)
        at /home/usr/vstsbuild/agent/utilities.js:13:19
        at FSReqWrap.cb [as oncomplete] (fs.js:226:19)

I believe I could resolve this by running the same command as sudo, but the agent cannot run in an elevated mode.

**Comment by bryanmacfarlane** [comment]
Check how you configured.  Installed globally should be run as root but stamping out an agent by running vsoagent-installer *should not*.  If you run that as root, then root will own the files (in _work etc...).  Next time you run as your account, you don't have permissions.  Follow directions closely.  Look who owns on the agent and _work folders and check permissions with ls -la
