### ISSUE TITLE
offline setup on Linux

### ISSUE THREAD

**Issue by hkamel** [Microsoft/vso-agent#156]
My customer has a policy around connect Linux servers to the internet and we are using TFS2015. I'm trying to install the prerequisite and the agent as well but it's really a painful process to setup everything offline.

do we have guidance on how we manage this is an offline environment?

**Comment by bryanmacfarlane** [comment]
>> painful process to setup everything offline.

which process are you referring to?

**Comment by bryanmacfarlane** [comment]
the agent is xcopy

**Comment by hkamel** [comment]
Agent will run in its own without the dependencies (node, npm) , the process I'm referring to is regarding the dependencies

**Comment by bryanmacfarlane** [comment]
node and npm have .tar.gz downloads and offline install policies.  closing as external
