### ISSUE TITLE
Issue configuring Agent on Linux Server

### ISSUE THREAD

**Issue by kp2015** [Microsoft/vso-agent#157]
Having issue configuring the agent.  Apologize if this is not the best place to request some input on the issue.

I'm unable to authenticate properly to my TFS server while configuring the VSO agent to our on premise TFS 2015 instance.  I've verified that my account is in both roles (admin / service account) for the Agent Pool and i'm as well an Admin in TFS itself.   

is there any IIS configuration that may be not configured properly to use the vso-agent for on premise?

I have an msdn forum post going currently which can shed some light on it:

https://social.msdn.microsoft.com/Forums/en-US/2e08ce0e-cf80-4f4f-9f80-f9e480fc84ce/tfs-2015-microsoft-cross-platform-build-agent-linux-server-configuration?forum=tfsadmin

This is TFS 2015 UPdate 1 RC2
Cent OS 7, 64 bit Linux Server
Agent version: 0.2.29 / 0.3.13 (tried with latest this morning)

Looking for any help to move this along to be able to start using.

Thanks

**Comment by bryanmacfarlane** [comment]
Yeah - I'll add a link to the front page of the readme today with complete instructions

But - you need basic auth in IIS: 
https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md

**Comment by bryanmacfarlane** [comment]
Also - see this issue - you have to set two envvars.  I'm fixing that workaround today.

https://github.com/Microsoft/vso-agent/issues/68

**Comment by kp2015** [comment]
Hi Bryan.

Thanks for the information. 

Are those just simply the user I plan on using , service account, to connect to TFS with? setting in the envars?

ETA on the NTLM. I don't see my system engineers letting me fly with basic auth for very long other than for testing purposes.

**Comment by bryanmacfarlane** [comment]
Early in the new year, we start a new single agent written in core CLR.  We won't add ntlm to the node one before that because it's throw away.

Until then, ensure you're using SSL.  What's the concern with basic auth if you use HTTPS?

**Comment by kp2015** [comment]
None if i used it.  Which is something I will be looking at.

Back to those envvars.  do those have to be set just for this communication to work with tfs?  I tried after after enabling the basic authentication and got same error.  So wanted to make sure understand completely.

Thanks

**Comment by kp2015** [comment]
Got it working now to the point i can now configure and get it up and running.  Thanks for the help with that part.

Next issue i see is how to get it run in the background / service all the time? Looking at the installation piece, there isn't a way yet for linux?

What options do i have at this point?

**Comment by bryanmacfarlane** [comment]
Your options are nohup, create your own init.d script (-u and -p on cmdline) or create your own docker container with options to start on startup.  That's what we will publish - a docker container on linux

**Comment by kp2015** [comment]
ok.  am i missing something then on how to start / stop this then without having to configure it everytime running node vsoagent  and entering in the parameters each time ?

hopefully my last question.

**Comment by bryanmacfarlane** [comment]
Just to confirm - you're getting asked all the config questions every time ?  I can't repro - see all the docs and videos.  After config it writes a .agent config file with your answers.  On restart it only prompts you for creds unless you pass via cmd line with -u and -p

**Comment by kp2015** [comment]
Ok. I see it now what was misleading me originally that i had to do it everytime.  I think we are good on this one at this point. Appreciate all the help.

Looking forward to seeing this become more robust in the future!
