### ISSUE TITLE
Building from a tag from a GitHub repository sets BUILD_SOURCEVERSION to "null"

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vso-agent#158]
When building from a GitHub repository and using a tag reference as the commit to build from (either `xxx` or `refs/tags/xxx`), the environment variable `BUILD_SOURCEVERSION` is never set.

Using `vsoagent-installer@0.3.13`. Seen both on Linux and OS X.

**Comment by joaomoreno** [comment]
This also happens when running a build from a generic git repository and building from **any branch**.

**Comment by joaomoreno** [comment]
I still see this... very sad. :(

**Comment by bryanmacfarlane** [comment]
scott can investigate

**Comment by bryanmacfarlane** [comment]
The new .net core agent (replacement for this one) is setting this.  It also has more features than this one.  Been busy on combining into the one agent

https://github.com/Microsoft/vsts-agent

Should try it out.

**Comment by joaomoreno** [comment]
Will do. Didn't realise you guys were so far ahead on that agent.
