### ISSUE TITLE
Error "Invalid resource " while configuring xplat build agent on mac

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vso-agent#161]
This happens while configuring the agent:

netcfs-mac-mini:buildagent netcf$ node agent/vsoagent.js
Enter alternate username > prawalagarwal
Enter alternate password > 
Enter server url > https://prawal.visualstudio.com
Enter agent name (enter sets netcfs-mac-mini.local) > Agent-Mac-Xcode
Enter agent pool name (enter sets default) > 
Error starting the agent
Invalid Resource
Shutting down host.

Are there any logs I should look for and can provide you?

**Comment by ankitgo** [comment]
What version of the agent are you using?

**Comment by ricardask** [comment]
This behavior was also observed when using http only proxy (corporate) to connect to vso project. No workaround yet.

**Comment by bryanmacfarlane** [comment]
We have an issue tracking corporate proxies in the agent replacing this one.  Please track that issue:  https://github.com/Microsoft/vsts-agent/issues/165
