### ISSUE TITLE
reconfigure the agent

### ISSUE THREAD

**Issue by kp2015** [Microsoft/vso-agent#163]
The agent was configured and working.  Went back to restart it, and couldn't get it to start.  i removed the agent from the agent pool and recreated.  At that point, i get the below.

node myagent/vsoagent

Enter alternate username>
Enter alternate password >
successful connect as undefined
Retrieved agent pool: Linux (3)
Error starting the agent
Agent was deleted.  Reconfigure

I'm not sure how at this point to reset things on the server so i can reconfigure?

Any help is appreciated.

**Comment by bryanmacfarlane** [comment]
delete the .agent file (that contains the configuration)

**Comment by bryanmacfarlane** [comment]
I'll update the docs

**Comment by kp2015** [comment]
Worked perfect. thanks Bryan.
