### ISSUE TITLE
can't access a secret variable in gulp 

### ISSUE THREAD

**Issue by SofianHn** [Microsoft/vso-agent#164]
I create a PAT as a secret variable. I use that token from within a gulp task through `process.env["VAR_NAME"]`

This variable is always empty on build time. Is this a known issue for node?

**Comment by bryanmacfarlane** [comment]
Not known - looking

**Comment by bryanmacfarlane** [comment]
Are you running on a windows agent or osx/linux?

**Comment by SofianHn** [comment]
I tried it on all platforms.

On Dec 5, 2015, at 8:04 AM, Bryan MacFarlane <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you running on a windows agent or osx/linux?

-

**Comment by joaomoreno** [comment]
Bump

**Comment by bryanmacfarlane** [comment]
Investigating ...

**Comment by bryanmacfarlane** [comment]
Secret variables need to be mapped into inputs of tasks.  They don't get set as vars

So on definition variables
mysecret=foo

On task (such as shellscript)
arguments="foo bar $(mysecret)"

Now it's available
