### ISSUE TITLE
Could not find task.json using xplat agent on Mac

### ISSUE THREAD

**Issue by silenz357** [Microsoft/vso-agent#165]
Hello, 

I am currently using on-prem TFS 2015 and the xplat vsoagent running on a Mac. On the TFS side I have a build definition with only a Xamrin.IOS build step that is configured to build a simple Hello World project. When sent to the build queue, the agent picks up the build request and fails immediately with the following error

 Error: Could not find task: /Users/michael/tfsAgent/_work/tasks/XamariniOS/1.0.3/task.json

Upon further investigation I see that the  /Users/michael/tfsAgent/_work/tasks/XamariniOS has been created for the build step and contains a 1.0.3.zip file that was extracted creating an empty folder. This because the zip file is also empty.

I have managed to work around this issue by cloning the vso-agent-tasks repo and coping the contents of Tasks/XamariniOS into the 1.0.3 folder. After submitting the job again (and using the oAuth workaround for on-prem described here https://github.com/Microsoft/vso-agent/issues/68) the project builds without issue.

I was hoping someone might provide some insight on what I can do to get this to work "out the box" so to speak and avoid piecing together the build agent.

Thanks

**Comment by bryanmacfarlane** [comment]
We have a PR https://github.com/Microsoft/vso-agent/pull/162 which we believe will fix this.

I'm testing today and I'll release a 0.4@preview hopefully today

**Comment by bryanmacfarlane** [comment]
Go ahead and kick the tires on preview.

I also updated the docs for on-prem:  https://github.com/Microsoft/vso-agent 

I'll be watching for issues

**Comment by silenz357** [comment]
So Far So Good. Thank You very much.

**Comment by bryanmacfarlane** [comment]
Thanks for confirming

**Comment by lukka** [comment]
I still have the error as originally reported in this issue. When i start my build from VSTS that contains a task "Copy and publish artifacts", the build stops when preparing task, and I get the following in the /Users/myusername/Library/Logs/vsoagent.myvsoaccount.agent31Oct2015/stdout.log

> [err]18:01:28 GMT+0100 (CET): ##[Error] 2016-01-19T17:01:28.208Z: Error: Could not find task: /Users/myusername/vso_agent/agent31Oct2015/_work/tasks/CopyPublishBuildArtifacts/1.0.13/task.json

The file task.json is not existent indeed.

Listing the packages in the agent directory reports the following:
myusername@hostname:~/path/to/agent31Oct2015$ npm list
vsoagent-installer@0.4.0 /Users/path/to/agent31Oct2015
├── adm-zip@0.4.7
├── async@0.9.2
├─┬ glob@5.0.15
│ ├─┬ inflight@1.0.4
│ │ └── wrappy@1.0.1
│ ├── inherits@2.0.1
│ ├─┬ once@1.3.3
│ │ └── wrappy@1.0.1
│ └── path-is-absolute@1.0.0
├── iniparser@1.0.5
├─┬ minimatch@2.0.10
│ └─┬ brace-expansion@1.1.2
│   ├── balanced-match@0.3.0
│   └── concat-map@0.0.1
├── minimist@0.2.0
├─┬ nconf@0.6.9
│ ├── async@0.2.9
│ ├── ini@1.3.4
│ └─┬ optimist@0.6.0
│   ├── minimist@0.0.10
│   └── wordwrap@0.0.3
├── node-uuid@1.4.7
├── q@1.4.1
├─┬ read@1.0.7
│ └── mute-stream@0.0.5
├── semver@5.1.0
├── shelljs@0.2.6
├── svchost@0.1.2
├─┬ svcinstall@0.2.1
│ ├─┬ plist@1.2.0
│ │ ├── base64-js@0.0.8
│ │ ├── util-deprecate@1.0.2
│ │ ├─┬ xmlbuilder@4.0.0
│ │ │ └── lodash@3.10.1
│ │ └── xmldom@0.1.21
│ └── shelljs@0.3.0
├── validator@3.11.2
├── vso-node-api@0.6.1
├─┬ vso-task-lib@0.5.5
│ ├─┬ glob@6.0.4
│ │ ├─┬ inflight@1.0.4
│ │ │ └── wrappy@1.0.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ once@1.3.3
│ │ │ └── wrappy@1.0.1
│ │ └── path-is-absolute@1.0.0
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.2
│ │   ├── balanced-match@0.3.0
│ │   └── concat-map@0.0.1
│ └── shelljs@0.3.0
└─┬ xmlreader@0.2.3
  └── sax@0.5.8

Any help?

**Comment by bryanmacfarlane** [comment]
@lukka - are you on-prem TFS server or VSO account?  Once tasks are downloaded by that version, it shouldn't download again.  If you delete the tasks version folder, it should trigger it to try again?  Does it repro everytime (at one point there was an intermittent issue in the zip lib or the service or etc... that wasn't tracked down)?  Also which version of node and which OS/version?

**Comment by lukka** [comment]
I am on a VSTS account, and i am using PAT for authentication. Using MacOSX 10.11.2.
node version v4.2.3. The issue is persistent, the task  must disabled from the build in order to succeed.
I will report what happen when deleting the task folder.

**Comment by lukka** [comment]
After a 
> rm -rf _work/tasks/
on the agent directory, i queued the same build with the CopyAndPublishArtifact task enabled, and everything started working again, and now the build always succeed.
Nevertheless i could not see in any log anything related to the 'repopulation' of the _work/tasks directory.

**Comment by bryanmacfarlane** [comment]
OK - I think it's a separate issue than this one (this was a specific on prem issue).  

Can you log another issue with these details?  What happens is we create a folder to download the task into and check that folder to see if we need to.  In the intermittent case where the download fails (server, network, client lib error etc...), you're stuck with a folder and it never tries again.  (if this is the issue I think it is).  What we need to do is write some sort of file to mark as done or download to the side and rename.

Let us know

**Comment by bryanmacfarlane** [comment]
@lukka 

OK - yep that's the workaround.  Log another issue about making task download robust to failures

**Comment by lukka** [comment]
Created issue #188
