### ISSUE TITLE
Getting Git LFS to work on build agents

### ISSUE THREAD

**Issue by StevenBroth** [Microsoft/vso-agent#167]
After an agent checks out the repository, the LFS files are still just pointers to the actual files. Thought it could just be my setup but its the same on the hosted agents. Interestingly the VSO repository explorer doesn't appear to support LFS either, showing broken images instead.

Are there plans to make the checkout on the agents automatically do a 'git lfs fetch'? Otherwise is it possible to create a build step that also has access to the git credentials?

Thanks

**Comment by bryanmacfarlane** [comment]
Is this for the xplat agent?

LFS isn't supported on either yet.  It's on our backlog.  However, xplat uses git.exe (where win/hosted uses libgit)so it's closer

**Comment by StevenBroth** [comment]
Wasn't aware of the xplat agent, but unfortunately I need to use the win version. Sounds like my best bet is to run a git command step, any chance there are some exposed git credential environment variables I can hook into?

**Comment by bryanmacfarlane** [comment]
In the sprint that's rolling out now (give it a week or so), there's an option in the definition options tab to give scripts access to the oauth token.  If you check that, the oauth token generated for the build will be exposed as a variable.  Check that and create a step to dump the envvars to see it.  you can use any username and that token as the password.
