### ISSUE TITLE
How to configure XPlat to for deployment only

### ISSUE THREAD

**Issue by BuddyWork** [Microsoft/vso-agent#170]
I would like to know if I can configure the XPlat agent on Linux so it only does deployment, I don't want it to carry out any builds. Is this possible?

I have a Windows Server with TFS and Release Management installed and got some applications that have to be deployed on Linux which are pre-built by the 3rd party which is why I just want to deploy it to the Linux Server.

**Comment by bryanmacfarlane** [comment]
The way to control the use of agents (in general - not just this specific scenario) is to put the linux agents in their own pool.  Then create a queue pointing to that pool and secure access to the queue.

**Comment by bryanmacfarlane** [comment]
Also note that capabilities and demands will ensure it doesn't pick up builds intended for a windows machine.  For example, if you have a windows build machines in the same pool and you build uses msbuild/VS task, it will demand an agent that has msbuild/VS.  So it's not like a linux machine intended for deployments would accidentally pick up a build intended for a windows technology.

**Comment by BuddyWork** [comment]
Can Microsoft Release Management talk to this agent
