### ISSUE TITLE
Running a build task without any inputs hangs indefinitely in x-plat agent

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vso-agent#171]
If you have a build task without any inputs, it works fine on the Windows agent. But on the x-plat agent, it hangs indefinitely when that step is executed, without any logging.

I've debugged into the agent code and determined that the error is in https://github.com/Microsoft/vso-agent/blob/master/src/agent/job.ts#L391. The _processInputs method throws if inputs is undefined, which causes the task to never run and the callback to never get executed, which causes the indefinite hang.

**Comment by jkeech** [comment]
I can also confirm that modifying the task to have an empty inputs array ("inputs": []), instead of not having an inputs property at all, fixes the problem. I think there are two potential fixes here:

1) Fix up the agent code to handle a task.json file correctly if it doesn't have an inputs property defined, or
2) Enforce that the inputs property is defined in the task.json file on upload. Have the server reject the task if it doesn't pass validation. The validation would require the inputs property to be defined.

**Comment by bryanmacfarlane** [comment]
Scott - I think we should fix service side as suggested but also protect agent side.

**Comment by bryanmacfarlane** [comment]
Can you try in the agent replacing this one?  https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
deprecated
