### ISSUE TITLE
Does Xplat work under Microsoft Release Manager

### ISSUE THREAD

**Issue by BuddyWork** [Microsoft/vso-agent#173]
I would like to know if Xplat works under Microsoft Release Manager.

**Comment by bryanmacfarlane** [comment]
Yes.  Version 0.3.13 and greater

**Comment by bryanmacfarlane** [comment]
And it's the new RM vnext

**Comment by BuddyWork** [comment]
Thx any examples?

**Comment by bryanmacfarlane** [comment]
I'll send to RM folks and ask for docs/videos etc. but it should work just like build vnext.  You create a def, add tasks and hook up an agent ( or use hosted )

Sent from Outlook<http://taps.io/outlookmobile>




On Sat, Jan 16, 2016 at 11:32 PM -0800, "BuddyWork" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thx any examples?

-

**Comment by ankitgo** [comment]
Here is a youtube video that can help you get started.
https://www.youtube.com/watch?v=82i78IHpl2A

I ll dig in for some docs in the mean time.

**Comment by BuddyWork** [comment]
Thx for the video link do you have an example how to use xplat just for releases with Microsoft Resource Management 2015 with xNext

**Comment by vsrm** [comment]
Please refer to http://blogs.msdn.com/b/visualstudioalm/archive/2015/11/28/deploy-artifacts-from-onprem-tfs-server-with-release-management-service.aspx for a step by step guide.
