### ISSUE TITLE
Install requires root...

### ISSUE THREAD

**Issue by rpural** [Microsoft/vso-agent#174]
In our environment the developers generally don't get access to root on the boxes. Is there a way to perform the installation into an alternate path, such that root would not be required to install the product? We can use root to install any required prereqs, and node and npm can be installed in an alternate path. Can this also be installed in an alternate path, and without the need to run as root?

**Comment by bryanmacfarlane** [comment]
The agent is ultimately xcopy.  The global install is just an npm distribution method to stamp out multiple agents on a box.  On a non prod box, do an npm install vsoagent-installer -g and then vsoagent-installer in a directory to stamp out an agent.  Copy that off to a thumb drive.

Now you can xcopy (cp -R) that anywhere on any machine without requiring root access on the build machine
