### ISSUE TITLE
Personal access token scope for running agent

### ISSUE THREAD

**Issue by vladigor** [Microsoft/vso-agent#175]
Hi, 
Your readme says that personal access tokens can be used to provide permissions for the VSO Agent to run (https://github.com/Microsoft/vso-agent#provide-permissions-to-account)
but the document doesn't mention which scopes are required.
I'd prefer not to have to create a token that is set to All Scopes

**Comment by chrisrpatterson** [comment]
It has to be all scopes as there is no specific scope assigned for the agent pools.

**Comment by bryanmacfarlane** [comment]
Scott - we need to register some agent urls to ensure scopes work

**Comment by nbering** [comment]
Any update on this? I tend to agree with @vladigor, making Personal Access Tokens that are scoped to everything isn't great security practice. Better than using my Microsoft account credentials, but it could be made even better by assigning a scope.

**Comment by bryanmacfarlane** [comment]
Yes.  The issue is with the service not the agent.  We have a bug on the backlog for the service
