### ISSUE TITLE
Why can't this be used on Windows?

### ISSUE THREAD

**Issue by SyntaxC4** [Microsoft/vso-agent#179]
It seems odd to me that this code should basically be supported on Windows, however, it is only allowed to be used on OSX and Linux workers. 

There is no way to publicly download the agent installer for Windows which makes it harder to install the agent on a Windows VM in an automated fashion.

**Comment by jarz** [comment]
This code doesn't (yet?) support NTLM, so maybe that's why. I tried using this agent on a Mac against TFS 2015 with basic auth enabled -- one person couldn't access TFS anymore and another couldn't see the list of queries. There be dragons, etc.

**Comment by bryanmacfarlane** [comment]
It can technically be used on windows.  But you have to understand there's a progression.  The windows agent is written in windows non portable .net.  This project was started to support linux/OSX and will culminate in one agent.

We're starting a port of this code base to xplat core CLR (we were waiting for that).  That allows us to unify the two code bases and create one.

Regarding NTLM - node is technically capable of NTLM but we're going the other way.  We're bringing OAuth to on-prem to ensure the platform is open and extensible beyond this language.  It also allows many scenarios where cross domain trusts etc.. were inhibitive.

We're targeting the next major release of TFS for this

**Comment by bryanmacfarlane** [comment]
The new one can: https://github.com/Microsoft/vsts-agent
