### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vso-agent#181]
I am currently using on-prem TFS 2015 preview and the xplat vsoagent running on a Ubuntu 14.04. On the TFS side I have a build definition with only a PublishTestResults build step. When sent to the build queue, the agent picks up the build request and fails immediately with the following error

Error: getaddrinfo ENOTFOUND MachineXYZ MachineXYZ:8080

Some info the ubuntu machine: I had to domain join this machine and setup ssh. Even when setting up the agent I had to provide the full domain name for server url. For eg:

**http://MachineXYZ:8080/tfs** didnt work.
**http://MachineXYZ.domain.com:8080/tfs** worked

I had to provide write permissions for the agent folder to the user (it was failing with "cannot create ./_work). What is the issue here?

**Comment by prawalagarwal** [comment]
modifying resolv.conf to contain the domain worked for me.

**Comment by Mittchel** [comment]
@prawalagarwal Where did you find the resolv.conf?
