### ISSUE TITLE
Agent will not reconnect after network interruption

### ISSUE THREAD

**Issue by tschleining** [Microsoft/vso-agent#182]
On OSX if you have the agent running interactively and the network connection is interrupted, the agent will never reconnect.  You have to kill the process an restart it.

**Comment by bryanmacfarlane** [comment]
That's not the case and I just reverified.

The agent opens an http long poll with the server listening for build messages.  It keeps looping and steps off 15 seconds at a time reconnecting.  Today I verified with disconnecting the network cables, closing the laptop, putting it to sleep etc...  Once it connected back up it started listening again.

A specific build can get interupted but the agent session will reconnect and listen for more messages.

If you have more details and trace logs (_diag folder under the agent) then reactivate.
