### ISSUE TITLE
Build fails when staging directory contains a file with long path

### ISSUE THREAD

**Issue by aplex** [Microsoft/vso-agent#185]
Build fails early without performing any steps when there is file with a long path left in staging directory from the previous build.

2016-01-08T04:02:50.6745350Z ##[error]Could not find a part of the path 'C:\BuildAgents\2\_work\16c4a738\staging\Package\Out\xyz\2016-01-07T10-52-03\1535-longpath-ReshareSubfolders.tdl\Alice\SyncFolder\AliceAAAAAAAAAAAAAAAA\AliceBBBBBBBBBBBBBBBB\AliceCCCCCCCCCCCCCCCC\AliceDDDDDDDDDDDDDDDD\AliceEEEEEEEEEEEEEEEE\BobFFFFFFFFFFFFFFFFFF'.

**Comment by ericsciple** [comment]
@aplex what version is your agent? It should be listed on the agent pools tab of the collection level admin portal. During which step does the failure occur? If you need a workaround, in very recent releases (92.0-ish?), a new build.clean variable was introduced: https://msdn.microsoft.com/en-us/Library/vs/alm/Build/scripts/variables . Prior to that, I believe setting clean on the repo tab of the definition was equivalent to build.clean=all

**Comment by aplex** [comment]
Agent.Version is 1.83.2. Failure occur at build start, before any of my steps are executed and even before source code is retrieved.

**Comment by ericsciple** [comment]
@aplex Does setting clean on the repo tab workaround the issue for you?

**Comment by aplex** [comment]
I already re-configured build to put folders with long path to TestResults that I clean manually after build completes, so I don't have this issues right now. But, generally, TFS should be able to delete folders regardless of long path content in them.

**Comment by bryanmacfarlane** [comment]
This repository is for the xplat (linux, osx) agent.  Closing.
