### ISSUE TITLE
Reconfiguration of vso-agent

### ISSUE THREAD

**Issue by TimMarlow** [Microsoft/vso-agent#186]
Hello,

The agent pool that was assigned to our Mac has been deleted and I'd like to re-configure the agent. When I try and run it at the moment I get: 'Error starting the agent, agent was deleted'

How can I run the configuration process again or do I remove and start again?

Thanks.

**Comment by bryanmacfarlane** [comment]
delete the .agent file

**Comment by TimMarlow** [comment]
Thanks!

**Comment by bryanmacfarlane** [comment]
ill doc today :)
