### ISSUE TITLE
VSTS on-prem agent could have an out of order '_worker/tasks' directory content

### ISSUE THREAD

**Issue by lukka** [Microsoft/vso-agent#188]
On MacOSX 10.11 and using an account on VSTS, using an on-prem vsts agent (installed by vsoagent-installer@0.4.0), the '_worker/tasks' directory could remain in an inconsistent state (e.g. tasks are partially downloaded due to network issue), and there is not way to restore the proper content of that directory but with its entire manual deletion. When the '_worker/tasks' directory is inconsistent some of the task's code misses entirely (or partially), leading to a sure failure of the 'Preparing tasks' build step, hence the build will fail too.

Please verify this conjecture and implement a mechanism to automatically identify an out of order  '_worker/tasks' directory and restore its content.

**Comment by bryanmacfarlane** [comment]
This is fixed in the new agent @ https://github.com/Microsoft/vsts-agent

It's replacing this one
