### ISSUE TITLE
Agent doesn't have all environment variables listed in the docs

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vso-agent#195]
The [VSTS Build documentation](https://msdn.microsoft.com/en-us/Library/vs/alm/Build/scripts/variables) lists variables that are available during the build's execution. Our Windows agents are getting all of these variables, but our Mac agent is missing several of them, such as the following:

AGENT_ID
AGENT_NAME
BUILD_REPOSITORY_CLEAN
BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT
BUILD_REPOSITORY_LOCALPATH
BUILD_REPOSITORY_NAME
BUILD_REPOSITORY_PROVIDER 
BUILD_REPOSITORY_URI
SYSTEM_DEFAULTWORKINGDIRECTORY

**Comment by bryanmacfarlane** [comment]
This should be fixed in the new replacement agent

https://github.com/Microsoft/vsts-agent
