### ISSUE TITLE
Failed Request: Not Found(404)

### ISSUE THREAD

**Issue by danieljgmaclean** [Microsoft/vso-agent#206]
Hi,

I have a build job which uses the tasks Command Line, Cordova Build and then HockeyApp. However the build is marked as a failure despite the fact all tasks executed successfully.

![screen shot 2016-02-03 at 10 47 11](https://cloud.githubusercontent.com/assets/985467/12780034/8706466c-ca63-11e5-856b-9a2bf1ac5f10.png)

When all 3 tasks are enabled, after the HockeyApp step completes, I can see in the logs that the HockeyApp task completes as seen below. I also checked HockeyApp and my binary was uploaded fine. However, the build is marked as a failure because it fails when it tries to upload a build summary document. Having looked at the source for the VSO-Agent I can see this is a task which isn't completed by HockeyApp task, but by the VSO-Lib itself.

Strangely, if I disable the HockeyApp step, it works fine. So i wasn't sure whether to post this problem to HockeyApp or here, so i'm going to start here first.

```
2016-02-03T10:19:17.719Z: Uploading summary file
##[Debug] 2016-02-03T10:19:17.746Z: task result: Succeeded
2016-02-03T10:19:19.009Z:  
2016-02-03T10:19:19.009Z: Start: Upload a build summary document
2016-02-03T10:19:19.009Z: End: Upload a build summary document
2016-02-03T10:19:19.009Z:  
##[Error] 2016-02-03T10:19:19.009Z: Failed Request: Not Found(404) - 
2016-02-03T10:19:19.009Z: Failing task since command failed.
```

**Comment by bryanmacfarlane** [comment]
Looks to be an issue with the HockeyApp task.
