### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/vso-agent#207]
Hi,
I am running on premise agent on Ubuntu machine.

Recently a fresh agent is throwing this on queuing a build:
Error: ENOENT: no such file or directory '/home/*****/myagent/agent/plugins/Build'

I am using the preview agent.

Thanks

**Comment by ColinDabritzViewpoint** [comment]
Interesting, we're seeing a version of this error with no file reference.

Particularly, we see this in our 'test publish' step, for a Xamarin UITest run.

The previous step completes, and we see a file iOS9.3_UITest.xml in the output.

The publish step errors out with:
`2016-04-20T15:48:42.853Z: [warning]Failed to publish test results: Could not read file (): ENOENT: no such file or directory, open ''`

This suggests an 'empty' file name or path, or perhaps some escaping issues around open?

We're pretty sure we didn't change the agent or the step, but VSTS sometimes publishes new versions of step scripts, so perhaps a change in that script about 7 days ago (around 4/13/2016) caused a bad interaction with the VSO-Agent.

**Comment by bryanmacfarlane** [comment]
I can't repro.  If it doesn't have plugins/Build that sounds like a corruption issue.  Reactivate if it repros with latest 0.6.x agent
