### ISSUE TITLE
Reconfigure on OS X

### ISSUE THREAD

**Issue by Alber70g** [Microsoft/vso-agent#21]
How to reconfigure on OS X?

There seems not to be a `node agent/vsoagent --help` to find how to reconfigure for another Visual Studio Online URL.

**Comment by bryanmacfarlane** [comment]
I used to have reconfigure but it was easier to simply create a new folder and install a new agent.  Delete the other one if needed.  Details below.

Two options:

1. create another one in another directory and wack the current agent directory (recommended and easiest)
2. reconfigure the existing directory:

you just have to delete the .agent file.  So:
rm .agent

If you're pointing to a new url, you'll likely want to cleanup some repos on disk (stuff in _work/build) 

Note:  If you're running as a service on osx, you need to stop it and uninstall the service.  That will remove the plist.  See the readme (svc.sh stop, svc.sh uninstall)

So, it's just easier to create a new folder, install the agent and configure.  delete the old agent if not needed. 

I'll update the readme.

**Comment by Alber70g** [comment]
I also have another issue when starting an agent on OS X. I tried on both my own and from another VSO to be an agent for the build process, but on both i get the response "Forbidden 403"

```
##[Error] 2015-06-09T17:14:26.132Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2015-06-09T17:14:26.132Z: Failed Request: Forbidden(403) - https://xxx.visualstudio.com/_apis/distributedtask/pools/1/sessions
```

**Comment by bryanmacfarlane** [comment]
That means you didn't add the account to the agent pool service accounts (403 creating session to listen to queue).

On the main readme, there's instructions.  There's also a video.

**Comment by Alber70g** [comment]
Oh sorry, I missed that part :+1:

**Comment by bryanmacfarlane** [comment]
np - I'll see if I can't make the error message/handling clearer.  thx

**Comment by vdangwal** [comment]
Agent Started.
##[Error] 2016-08-10T17:19:23.834Z: Message Queue Error:
##[Error] 2016-08-10T17:19:23.834Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2016-08-10T17:19:23.834Z: Message Queue Error:
##[Error] 2016-08-10T17:19:23.834Z: Failed Request: Forbidden(403) - Access denied. Digital Solutions needs Listen permissions for pool Default to perform the action. For more information, contact the Team Foundation Server administrator.

Could anyone please help? this is in premises Mac VM using VMWare.

**Comment by bryanmacfarlane** [comment]
@vdangwal - create another issue and fill out the template

**Comment by vdangwal** [comment]
@bryanmacfarlane  Issue #316 has been created. Please let me know if you need any information.
