### ISSUE TITLE
On-premise - Failed to find api location for area: distributedtask id: 60aac929-f0cd-4bc8-9ce4-6b30e8f1b1bd

### ISSUE THREAD

**Issue by rrudduck** [Microsoft/vso-agent#210]
This started after upgrading to the preview version of the agent. The agents are able to register correctly and they show up green in the agent queue. Our TFS installation is running 2015 Update 1. Any thoughts on where to start troubleshooting this?

**Comment by hounddog22030** [comment]
I got past this error by removing the Collection from the URL, e.g. http://tfs:8080/tfs/MyCollection -> http://tfs:8080/tfs

**Comment by bryanmacfarlane** [comment]
Yes, collection should not be in the config url
