### ISSUE TITLE
running Xplat Agent as a service (Linux) (On premise)

### ISSUE THREAD

**Issue by kp2015** [Microsoft/vso-agent#211]
What are my option for running this as a service or keeping it up all the time?

Currently i also see every time i do ./run.sh  it asks for the username / password.

Anyway we can get it so it doesn't prompt for those 2 pieces? How do i store them so the tool finds them? Command line argument?

What are the options.

Additionally What does the 'basic' mean during configuration?  true? false?

**Comment by ajibarra** [comment]
I had to hardcode username/password in sh to make it work. This is a must-have.

**Comment by bryanmacfarlane** [comment]
This is enabled in the new one agent that's replacing this.  https://github.com/microsoft/vsts-agent  It's about to go into preview

**Comment by bryanmacfarlane** [comment]
The replacement for this agent supports running as a service. We are releasing a new preview tomorrow or early next week. It already has more features than this one

https://github.com/Microsoft/vsts-agent
