### ISSUE TITLE
Arguments to run.sh not propagated to node process

### ISSUE THREAD

**Issue by couven92** [Microsoft/vso-agent#213]
Previously (before we had run.sh) you started the VSO Agent by calling `node agent/vsoagent`.

When doing that you could specify switches that configure the agent. E.g. `-u <alternate username>`

The guide for On-Premises-deployment (https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md) states that you should invoke `./run.sh` to start the agent. The arguments specified to `run.sh` are not propagated to the node process that `run.sh` starts.

Since `run.sh` currently does no more than start the node process in the way we used to before, this can easily be circumvented by invoking the agent old-style with `node agent/vsoagent`.
However, if `run.sh` ever should become a more complicated script, it should pass on command-line arguments to the agent

**Comment by bryanmacfarlane** [comment]
This is fixed in the new agent replacing this one

https://github.com/Microsoft/vsts-agent
