### ISSUE TITLE
Cannot read property 'mappings' of null

### ISSUE THREAD

**Issue by igorguga** [Microsoft/vso-agent#218]
I installed the xplat agent on a Oracle Linux machine. The machine did't have internet access, so folow the instruction of https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md#agents-without-internet-access. But the machine I used to download the agent was CentOS 7.

The agent started with no problem, but when I start a build, I got some errors like this on the shell:
/bin/sh: -c: line0: unexpected EOF while looking for matching ...

And the build log fails with this error, after the workspace was created:
_**##[Error] 2016-02-15T15:39:16.645Z: Cannot read property 'mappings' of null**_

If I repeat the build, I got the error: 
**_An error occurred: The workspace ws_2_17;TFSBuild already exists on computer jbpaqmssr001
_**
So I delete the workspace with the command **tf workspace -delete** and queue the build again, and it fails again the error: **_##[Error] 2016-02-15T15:39:16.645Z: Cannot read property 'mappings' of null_**.

What can be happening?

**Comment by yacaovsnc** [comment]
Did you install the preview agent or the regular agent?  Can you please check to see if you have a runtime/tee/tf script in your agent folder?

If you do, can you try running that tf script?  Do you get a list of help commands?  If you do, can you try running 'tf eula" and accept it?  

If it's preview agent, which version is it?  We fixed something similar in vsoagent-installer 0.5.5, I want to make sure you have the latest code.

**Comment by igorguga** [comment]
I got the agent from the link http://aka.ms/xplatagent like described at https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md#install. It's supposed to be the regular, right? The agent version appears as 1.999.0 in TFS.

Yes I have a runtime/tee/tf in the agent folder and I can run the script. Running **tf eula** informs that I already have accepted the terms.

But in the PATH, I included the **TEE-CLC-14.0.2** folder. Not the runtime/tee.

**Comment by igorguga** [comment]
I installed the preview version of the agent and I got the same errors, even the "workspace already exist" error. I notice that the preview don´t require the TEE-CLC on the PATH, but I got the same errors.

**Comment by igorguga** [comment]
Here are the logs I mentioned:

![basherrors](https://cloud.githubusercontent.com/assets/13902880/13056980/472c5a62-d400-11e5-87b3-61a0e4713401.png)

[firstTime_prepareWorkspace.txt](https://github.com/Microsoft/vso-agent/files/131239/firstTime_prepareWorkspace.txt)

[secondTime_prepareWorkspace.txt](https://github.com/Microsoft/vso-agent/files/131240/secondTime_prepareWorkspace.txt)

**Comment by igorguga** [comment]
The issue seems to be related with the environment... Oracle Linux is supported? I know that it is a variant of RedHat, but... 

In the other hand, is there any special permission requirement that aren't documented yet? Maybe in Oracle Linux some permissions can be diferent...

**Comment by igorguga** [comment]
@yacaovsnc after trying a lot of things with no success, I went in the direction of permissions, so I set up the agent with the **TFS Service Account**. For my surprise (or not) after that, everything worked perfectly.

The account I was using have this group membership:
![tfsbuildgroupmembership](https://cloud.githubusercontent.com/assets/13902880/13065478/e8cb8f58-d443-11e5-9919-714f3e8f6994.png)

I use this account for agents running on Windows with no problem. 

The account is also member of the groups **Agent Pool Administrators** and **Agent Pool Service Accounts** for my Linux Pool Agents.

I tried to put the build account as member of **Team Foundation Administrators**  but it had no effect, the same errors over again.

Any guess?

**Comment by yacaovsnc** [comment]
@igorguga just to confirm, did you reconfigure the agent yesterday?

I am not familiar with the permission requirement.  You could also fix "The workspace ws_2_17;TFSBuild already exists on computer jbpaqmssr001" issue with reconfiguring the agent.   This error indicates the workspace already exists somewhere else.  The workspace format is "ws_sourcefolder_agentId".  If you just copied over the entire agent folder, then the agent id is preserved and you will run into this problem (I assume jbpaqmssr001 is the where the original agent resides).  By running the configure.sh script, we will assign a different agent id and we won't hit the naming collision anymore.

**Comment by igorguga** [comment]
I resolved the workspace issue deleting the workspace. Good to know that the reconfigure assign a new Id to the agent. 

Now that I got the agent running (even with the service account), I'm only worried with the **Cannot read property 'mappings' of null**. This seems to be a bug. If it was related to permissions, the error message could express the problem better. When this happened, the shell messages indicated **unexpected EOF**. 

I think it worth a deep investigation.

**Comment by bryanmacfarlane** [comment]
That's coming out of the TEE command line (not the agent).  Yang is on that team.

**Comment by yacaovsnc** [comment]
@igorguga just want to confirm with you, do you still see the "cannot read property 'mappings' of null" error message anymore?

That error came from the fact the workspace is not created properly, and essentially we had a null pointer bug when trying to read the mappings from this non existent workspace.

**Comment by igorguga** [comment]
Yang,

 

I’ll update my agente and test. 

Thank you for the reply.

 

Igor

**Comment by bryanmacfarlane** [comment]
Is this fixed?  

Can you try in the new agent drop: https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
Ping.

**Comment by bryanmacfarlane** [comment]
deprecated.  new agent @ https://github.com/Microsoft/vsts-agent/blob/master/README.md
