### ISSUE TITLE
How to release a lock created by agent

### ISSUE THREAD

**Issue by ajibarra** [Microsoft/vso-agent#219]
Hi,

If for some reason I lose the session in my server, the agent dies and the lock is kept into my account. Then when I try to start again the agent I get:

`##[Error] 2016-02-15T20:59:37.403Z: Message Queue Error:
##[Error] 2016-02-15T20:59:37.404Z: Could not create an agent session.  Retrying in 15 sec
##[Error] 2016-02-15T20:59:37.404Z: Message Queue Error:
##[Error] 2016-02-15T20:59:37.404Z: Failed Request: Conflict(409) - The task agent v3t-apps already has an active session for owner d3418830-d2e1-11e5-93f2-773889b3967e.`

Even after several days I still get the same. Previously I have removed the agent from my account and created it again but I guess there is a better way to do that.

Thanks

**Comment by bryanmacfarlane** [comment]
That's not a lock.  The lock gets released.  If you're getting a conflict 409, it means there's another agent actively listening using that agent name.  If the session is active (that's what message says), it will correctly block forever
