### ISSUE TITLE
Agent not starting on reboot

### ISSUE THREAD

**Issue by Mittchel** [Microsoft/vso-agent#223]
Hi,

I've been trying to think of a strategy where we can use one Mac with multiple accounts (and each account one agent) in order to support the build for multiple apps. We want it this way since this will separate all iOS profiles/certificates for each project.

I have been following the docs with Xplat On permise: https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md

Agent is connected like a charm, but when I run it as a Daemon: ./agent/svc.sh install 
It says it's running, but as soon as I reboot the server(mac) and login it doesn't connect back until I manually do a restart. What can be the problem here?

Also, if I want to have multiple account's, I really do not want to login EACH account as soon as the server reboots so I thought running them as a Daemon and only auto-logon the HEAD account should do the trick, right?

**Comment by Mittchel** [comment]
Some extra info: 
--------------------------------------------
started (193) - 1 starts
--------------------------------------------
[err]11:41:21 GMT+0100 (CET): Error starting the agent
[err]11:41:21 GMT+0100 (CET): getaddrinfo ENOTFOUND mytfshost.com mytfshost.com:443
[out]11:41:21 GMT+0100 (CET): 
Shutting down host.

​

**Comment by bryanmacfarlane** [comment]
we are focusing on optimizing for many accounts/agents starting as launch agents with the new agent @ https://github.com/microsoft/vsts-agent which is about to go into preview

**Comment by bryanmacfarlane** [comment]
vsts-agent is the path forward.  Everything is scoped to an account so you can run many under different accounts on the same machine
