### ISSUE TITLE
Issues with VSO build definition for Mac

### ISSUE THREAD

**Issue by RajuChowdhury84** [Microsoft/vso-agent#227]
We have the below few strange issues with the build definitions that run on Mac:
 
1.     Build step name changes to CmdLine after execution: If we have a  command line build step named “git reset” and then when the build step gets executed the name gets changed to CmdLine. The problem is that we can’t easily identify which command line step failed as all the steps shows up as CmdLine after execution.
2.     Build step name gets randomly pascal cased: If we have a build step named “git pull” (all lower case), the build step shows up as Pascal cased (Git Pull). This does not happen on all the build steps.
 
Are you aware what’s going on with these? As mentioned it gets knotty for us to find out which build step in the build failed as all the of the properly named command line steps appear as CmdLine after execution.
 
If you want we can send a video as well which will show how the build steps (project: domoreexp) change after execution.

**Comment by RajuChowdhury84** [comment]
The version in package.json is “0.3.13”.

**Comment by bryanmacfarlane** [comment]
This is fixed in 0.6.x agent
