### ISSUE TITLE
tl.exec fails on linux and succeeds on windows when arguments are accessing another file in task folder

### ISSUE THREAD

**Issue by mvvsubbu** [Microsoft/vso-agent#228]
Task folder has file1.js, sample.jar and run the following command using 

tl.exec("java", " -classpath sample.jar:/usr/home/: Main" 

The above command works on windows and fails on Linux saying Main class not found.  This one is an issue because of the relative path of the sample.jar. In windows node handler is setting the current working directory to the task current version folder, where as on Linux it is not doing.

**Comment by yacaovsnc** [comment]
I am always using "java.arg(path.join(__dirname, sample.jar'));" whenever I needed to specify a jar packaged in the task.  

Would that help?

**Comment by mvvsubbu** [comment]
Yes I am fixing that way. But given that it is general issue for any task, fixing it in agent makes more sense, similar to how windows agent is doing.

**Comment by mvvsubbu** [comment]
I got a confirmation from Bryan saying this designed to like this and hence closing the issue
