### ISSUE TITLE
403 Access denied in on-prem deployment

### ISSUE THREAD

**Issue by ThomasKue** [Microsoft/vso-agent#23]
I read your instruction and I had created two accounts before.

Did you have any suggestion?

Regards
Thomas

![agent2](https://cloud.githubusercontent.com/assets/12827826/8129353/bb7a2f36-1108-11e5-9260-cfa6480ca50a.png)
![agent0](https://cloud.githubusercontent.com/assets/12827826/8129352/bb7a28d8-1108-11e5-8b1f-9d71a7e8611b.png)
![agent1](https://cloud.githubusercontent.com/assets/12827826/8129354/bb7f3792-1108-11e5-9cc9-040cbc2cfc4e.png)

**Comment by bryanmacfarlane** [comment]
Basic Auth needed.  Ensure you use a domain account or if workgroup, ensure that account user/pass you are using exists on the TFS server.

I'll verify today, but links relevant to the issue:

http://blogs.teamfoundation.co.za/2015/05/installing-and-configuring-tfs-2015-on.html

http://serverfault.com/questions/474882/how-do-i-enable-basic-authentication-for-iis-8-in-windows-server-2012

http://blogs.msdn.com/b/david_burgs_blog/archive/2013/11/05/installing-adding-iis-windows-authentication-feature-in-windows-8.aspx
