### ISSUE TITLE
All the messages written by child process are not showing up in console log

### ISSUE THREAD

**Issue by mvvsubbu** [Microsoft/vso-agent#233]
Invoking a child process using tl.exec in windows all the logs are showing up properly. But with cross plat agent only part of the logs are coming. See attached logs

[LinuxLogs.txt](https://github.com/Microsoft/vso-agent/files/148221/LinuxLogs.txt)
[WindowsLogs.txt](https://github.com/Microsoft/vso-agent/files/148220/WindowsLogs.txt)

**Comment by TingluoHuang** [comment]
@mvvsubbu what is your xplat agent version?
