### ISSUE TITLE
Agent must handle both "\" and "/" in file path input parameter.

### ISSUE THREAD

**Issue by ankitgo** [Microsoft/vso-agent#237]
we should resolve the slashes properly. Currently '/' only works.

**Comment by nigurr** [comment]
@ankitgo it's task specific. Can you raise the issue with specific task [vso-agent-tasks]

**Comment by ankitgo** [comment]
task specific? why?

**Comment by bryanmacfarlane** [comment]
Only a / is a path delimiter for this agent.  If you have a specific config, scenario blocking issue, outline it and reactive
