### ISSUE TITLE
ErrorConnectingToTheServer  Forbidden

### ISSUE THREAD

**Issue by DanHibbert** [Microsoft/vso-agent#239]
Hi, when I run vso agent from powershell I see the problem
ErrorConnectingToServer
Forbidden

.\Agent\VsoAgent.exe "/Configure" "/RunningAsService" "/ServerUrl:https://*****.visualstudio.com" "/Name:agent-****" "/PoolName:Default"  "/Login:****@****,****;AuthType=PAT" "/WindowsServiceLogonAccount:NT AUTHORITY\NETWORK SERVICE" "/WindowsServiceLogonPassword" "/WorkFolder:c:\agent\_work" "/Force"

The log file shows
15:53:58.121237 Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Forbidden

Does my account on VSTS need to be in a certain group?  If I goto https://***.visualstudio.com/DefaultCollection/_admin/_AgentQueue?queueId=1&_a=roles
my account is in Agent Queue Administrators and Agent Queue Roles

**Comment by bryanmacfarlane** [comment]
This is the node xplat agent.  The output from above is from the windows agent.

Are you still having the issue? I can forward but it's not an issue with this repo ...
