### ISSUE TITLE
TfsVC support

### ISSUE THREAD

**Issue by ThomasKue** [Microsoft/vso-agent#24]
Thanks for the clarification, now the agent started.

But now, I get this:
******************************************************************************
 Preparing tasks
******************************************************************************
******************************************************************************
 Running prepareWorkspace
******************************************************************************
preparing Workspace
cwd: /home/XXXXXXX/myagent/_work/build/573660dfef5a6fd833ad7433f6934387b698f979dd7311701c49868c971c8e55
##[Error] Unsupported repository type:TfsVersionControl

Please be so kind and tell me, whats going wrong.

Regards
Thomas

![debian8agent1](https://cloud.githubusercontent.com/assets/12827826/8129377/060c3012-1109-11e5-958f-3b66d734e25a.png)
![debian8agent2](https://cloud.githubusercontent.com/assets/12827826/8129379/061246d2-1109-11e5-8874-5d70eb3d560f.png)

**Comment by bryanmacfarlane** [comment]
TfsVC support is in a pull request right now and coming soon.  Will close when it's in

**Comment by davidclarencelim** [comment]
@bryanmacfarlane Thanks for this great project! Any ETA on when the pull request will be completed? We're waiting for this feature to get our iOS build going.

**Comment by haxu** [comment]
Hello,

I am trying to configure xplat CI agent for Java, C++ etc. But facing some known issue. 
1. TfsVC not support.
2. Git repo Authentication failed for IIS Basic Authentication.
So which means we cannot use vso-agent for on-premise TFS right now? Or do we need some additional configure for TFS server?

I am seeing TfsVS support on the pull request so I want to confirm when it will be release?

**Comment by bryanmacfarlane** [comment]
This is merged into master.  Note that we're testing now.  I will release a beta version to npm this week.

**Comment by dylanberry** [comment]
Was this released to npm? I installed today and I'm getting the same message: "TFS Version Control is not supported on xplat yet".

**Comment by bryanmacfarlane** [comment]
See the bottom of the readme about the @preview version (0.3.0) which was pushed recently.  It's under testing today - a bunch of stuff collided in master so I asked them to re-test tfsvc.  If you want to try it out, feel free.  We'll jump on any issues

**Comment by bryanmacfarlane** [comment]
sudo npm install vsoagent-installer@preview -g

**Comment by dylanberry** [comment]
Thanks Bryan, I'll give it a try.

**Comment by bryanmacfarlane** [comment]
Here's the big change - since tfsvc enforces path limits (even from TEE on *nix), we had to shorten the paths and get rid of the sha1 in the path via a mapping abstraction:

Details so you know what's going on:
https://github.com/Microsoft/vso-agent/blob/master/docs/workfolder.md
