### ISSUE TITLE
Configuring the agent fails with Bad Request (400) - duplicate envvars differing by case

### ISSUE THREAD

**Issue by DRCawthon** [Microsoft/vso-agent#245]
When we pulled PREVIEW and tried to ./run.sh on CentOS7 we got an error about Bad Request (400): An item with the same key has already been added.

The agent would not start.

We looked in ENV variables and noticed that HTTP_PROXY/HTTPS_PROXY/NO_PROXY was in there multiple times in both upper and lower case. 

Solution was to unset the lower case duplicates then we could start/configure the agent.

**Comment by DRCawthon** [comment]
![centos7 agent issue](https://cloud.githubusercontent.com/assets/8449701/13619002/2471d81c-e544-11e5-95ad-b373878cdd3c.jpg)

**Comment by DRCawthon** [comment]
![centos7 agent issue](https://cloud.githubusercontent.com/assets/8449701/13619073/7a368504-e544-11e5-8c09-b347b2308d2d.jpg)

**Comment by bryanmacfarlane** [comment]
I'll fix - capabilities should be case insensitive on Linux

**Comment by bryanmacfarlane** [comment]
The replacement for this agent does not have this issue. We are releasing a new preview tomorrow or early next week. It already has more features than this one

https://github.com/Microsoft/vsts-agent
