### ISSUE TITLE
Azure cloud service deployment template fails staging deployment when diagnostics is used

### ISSUE THREAD

**Issue by kaspernortoft** [Microsoft/vso-agent#25]
The Azure cloud service deployment script fails the second deployment if the service uses the diagnostics extension and is swapped from staging to production.

ConflictError: The extension ID RoleName-PaaSDiagnostics-Staging-Ext-0 is already in use for this deployment.

It seems possible to use the Set-AzureServiceDiagnosticsExtension instead to set the diagnostics, but it is pretty slow

**Comment by jeffyoung** [comment]
Thanks for reporting this issue.  I went ahead and moved it to https://github.com/Microsoft/vso-agent-tasks/issues/254 as it is an issue with the tasks and not the xplat agent.
