### ISSUE TITLE
Add Better Logging for a Task has no Available Execution Options

### ISSUE THREAD

**Issue by darthtrevino** [Microsoft/vso-agent#257]
For example, when I try to use the 'Report Code Coverage' build step, I get an immediate build failure in VSO with no clue as to what went wrong. Only by installing the VSO-Agent locally and seeing what was happening was I able to figure out that it required PowerShell, which is not available on our Linux build box. 

This log view should display an info message about not being able to find an appropriate execution option, and what options it has available.

![screen shot 2016-03-15 at 2 57 31 pm](https://cloud.githubusercontent.com/assets/113544/13795489/5b4be966-eabe-11e5-9d48-82b1a7f2481a.png)

**Comment by bryanmacfarlane** [comment]
The task should demand the capabilities it needs and it would never make it to the agent.  I believe the agent will log but we will look at making the communication clearer here in the replacement for this agent: 

https://github.com/Microsoft/vsts-agent

**Comment by darthtrevino** [comment]
I've only been looking at this today, but when I add my Macbook to our build queue I was able to do some log-debugging to see that the build fails when trying to report coverage because PowerShell is not an available handler. (https://github.com/Microsoft/vso-agent/blob/07e3e08a1c6f5ac574e71722dfe154bf9bd9b0fd/src/agent/job.ts#L356)

I'll keep an eye out for the replacement, thanks @bryanmacfarlane !
