### ISSUE TITLE
Authentication failed (required domain name)

### ISSUE THREAD

**Issue by lboss75** [Microsoft/vso-agent#258]
I have TFS 2015 installed in network with Active Directory. When I tring to build my code on Linux machine (CentOS) I have error:

fatal: Authentication failed for 'http://username:password@tfs/tfsserver/DefaultCollection/_git/project/'
/usr/local/git/bin/git failed with return code: 128

The problem is user name: it is without domain name.

But if I specify domain name, tfs agent escapes domain name separator (@ or \\) and I got error again:

fatal: Authentication failed for 'http://username%40**domain_name**:password@tfsserver/tfs/DefaultCollection/_git/project/' 

In console command 
git clone http://username@domain_name:password@tfsserver/tfs/DefaultCollection/_git/project/

works Ok.

So:
1. Can I tune TFS to accept only user name in the git?
2. Can I turn out escaping in the user name for git?

**Comment by bryanmacfarlane** [comment]
Did you follow all the on-prem instructions?

https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md

**Comment by ericsciple** [comment]
Setting the "Default domain" for the Basic Authentication settings in IIS might workaround the issue.

**Comment by lboss75** [comment]
Yes: I followed all the on-prem instructio. And yes: I set default domain in IIS.

**Comment by lboss75** [comment]
I have solved it:
Need to use NTLM authenfication in TFS.
