### ISSUE TITLE
Can't upload individual files via "artifact.upload"

### ISSUE THREAD

**Issue by HSAR** [Microsoft/vso-agent#263]
The artifact.upload command works on Windows with both directories and files, but vso-agent on Linux fails on files with "ENOTDIR: not a directory, scandir '$fileToUpload'".

This can immediately be observed in production by starting up a Linux agent, creating a build on VSTS with the "Publish Build Artifacts" task, and targeting a single file. The "Copy and Publish Build Artifacts" task does not suffer from this as it uploads the entire staging directory at once.

**Comment by satish-chandra** [comment]
+1

I am also facing the same issue. Please do let me know which log files I should attach that can help in debugging the issue.

**Comment by bryanmacfarlane** [comment]
Please open this issue in the task repo - it's not an agent issue 

https://github.com/Microsoft/vso-agent-tasks

**Comment by TingluoHuang** [comment]
I took a look, it is bug in artifact.upload command handler, we always trade the path input as folder and try to get all files under that folder.

**Comment by HSAR** [comment]
Any news on this?

**Comment by bryanmacfarlane** [comment]
Try the newly previewed agent.  It doesn't have this bug.  As long as you're on the service (visualstudio.com) you can use the new agent.  It will preview for on-prem later

https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
Did the replacement agent work for you?  If not, can you open an issue there?

**Comment by HSAR** [comment]
The replacement agent is working fine, as far as I'm aware.
