### ISSUE TITLE
Cent OS ECONNRESET on job build

### ISSUE THREAD

**Issue by hyouhaku** [Microsoft/vso-agent#264]
Environment: CentOS 7
First a few builds went though, but at one point it started to fail every single time.

2016-03-24T21:26:40.090Z: Running job: Build
unhandled:read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at Pipe.onread (net.js:546:26)
##[Error] 2016-03-24T21:26:44.816Z: worker unhandled: read ECONNRESET
##[Error] 2016-03-24T21:26:44.816Z: Error: read ECONNRESET
##[Error] 2016-03-24T21:26:44.816Z:     at exports._errnoException (util.js:856:11)
##[Error] 2016-03-24T21:26:44.816Z:     at Pipe.onread (net.js:546:26)

**Comment by hyouhaku** [comment]
I've sent you an email, thanks for the help

**Comment by bryanmacfarlane** [comment]
For some reason I missed.  Can you resend or reply?

**Comment by hyouhaku** [comment]
hi Bryan, restarting agent didn't help. I also tried to download logs from agent but it was empty, so we are blocked right now.
Only error message I have from centos console is:

[vsoagent@centos1 ~]$ ./run.sh
successful connect as undefined
Retrieved agent pool: Default (1)
Sat Apr 02 2016 23:20:31 GMT-0500 (CDT) : PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
centos1
2016-04-03T04:20:33.226Z: Agent Started.
2016-04-03T04:21:04.140Z: Running job: Build
unhandled:read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at Pipe.onread (net.js:546:26)
##[Error] 2016-04-03T04:21:04.880Z: worker unhandled: read ECONNRESET
##[Error] 2016-04-03T04:21:04.880Z: Error: read ECONNRESET
##[Error] 2016-04-03T04:21:04.880Z:     at exports._errnoException (util.js:856:11)
##[Error] 2016-04-03T04:21:04.880Z:     at Pipe.onread (net.js:546:26)

**Comment by bryanmacfarlane** [comment]
email me the _diag and _work/_diag logs (don't attach here)
also send me version (in package.json) of agent

**Comment by hyouhaku** [comment]
hi Bryan, please see attached file. Cheers

Bo

On Thu, Apr 21, 2016 at 11:25 PM, Bryan MacFarlane <notifications@github.com

**Comment by bryanmacfarlane** [comment]
This is fixed in the replacment agent: https://github.com/Microsoft/vsts-agent

Thanks for reporting!
