### ISSUE TITLE
Support referencing other variables when defining a build variable

### ISSUE THREAD

**Issue by mcm-ham** [Microsoft/vso-agent#271]
I'd like to be able to define a build variable for our staging builds like this:
```
Version = 0.6.$(Build.BuildNumber)
```
I can use $(Version) as an input to build tasks and it works fine, but not as an environment variable in scripts because its `0.6.$(Build.BuildNumber)` instead of `0.6.58`.

**Comment by rusty21** [comment]
I would also like this feature

**Comment by bryanmacfarlane** [comment]
This is coming in the new agent which is about to go into preview

https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
Closing since it's in the new agent and we won't be adding to this agent.  Should try and preview the new one.  We're also doing a new preview drop this week
