### ISSUE TITLE
Publish Test result doesn't work on Linux for TFS 2015 Update 2

### ISSUE THREAD

**Issue by lboss75** [Microsoft/vso-agent#278]
After update to TFS 2015.2 Publish test result is broken:

Test Results
No test runs available for this build. 

Task is publish test result JUnit format.

In tfs 2015 update 1 it works.

**Comment by nigurr** [comment]
Hi,

Which version of Xplat agent are you using?
TFS 2015 U2 tasks are compatible with Xplat Agent 0.5.x version 

If you are using latest Xplat agent, you need to use latest Publish Test Result task from https://github.com/Microsoft/vso-agent-tasks

**Comment by lboss75** [comment]
I use  Xplat Agent 0.5.9.
I have updated all yesterday (by curl -skSL http://aka.ms/xplatagent | bash).

**Comment by nigurr** [comment]
Hi,

When you execute the above command, it will install the latest Agent version which is [0.6.x], which is incompatible with old "PublishTestResults" task. 

Either you should explicitly download the Agent from here - https://github.com/Microsoft/vso-agent/releases  [0.5.10] or you need update PublishTestResults task in your TFS from here https://github.com/Microsoft/vso-agent-tasks/

If you need help in the second choice, let us know.

**Comment by nigurr** [comment]
This issue is fixed in latest master and should be available in next Xplat release. Closing the issue
