### ISSUE TITLE
Publish Code Coverage Results broke Linux build

### ISSUE THREAD

**Issue by lboss75** [Microsoft/vso-agent#279]
I trying to use Publish Code Coverage Results task in build definition on Linux.
It is broke build to clear screen
![image](https://cloud.githubusercontent.com/assets/17897525/14378639/bbddf774-fd7e-11e5-9a15-9890e74a64b7.png)

**Comment by nigurr** [comment]
We don't support Publish Code Coverage results for TFS 2015 U2.
Please let me know if you have any other query?
