### ISSUE TITLE
Can we authenticate using a VSO service account?

### ISSUE THREAD

**Issue by jeyoor** [Microsoft/vso-agent#28]
The demo video and written instructions seem to assume that the client will use Alternate Authentication Credentials set by a user with a Windows Live ID from Profile -> Credentials. [Currently basic auth?]

Is it possible to use a Visual Studio Online service account instead? [We would like to avoid builds running under credentials of a named user and lock down access as much as possible.]

We were able to provision a service account using IAccessControlService.ProvisionServiceIdentity, but I'm not sure how to set Alternate Authentication Credentials for it...

Some posts elsewhere seem to indicate that it is impossible to authenticate as a service account via basic auth and Windows Authentication is required instead. 
I.e. [comments here](http://nakedalm.com/getting-service-account-vso-tfs-service-credential-viewer/#comment-2063459809)

**Comment by bryanmacfarlane** [comment]
In the coming sprints, personal access tokens (like github) is getting rolled out to VSO.  They are revokable and you can add specific ones.  The only xplat (linux, OSX) mechanism will be those for the near future.
