### ISSUE TITLE
Mac agent with External git doesn't build with fresh environment

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vso-agent#286]
We've got a Mac build agent provisioned as a build server and we've tied the build definition to an External Git repo.

When we do builds, we've found that we get the `git clean -fdx` error message, but we've then noticed that it does the entire build **against an old version of the source** - this is to say that `_work/s` only has one directory under it (in our case "2") and it's reused between builds.

This seems like bad practice; I would prefer each build gets done in its own "clean" space and we maintain `_work/s/#` up to the retention policy limit.

**Comment by nigurr** [comment]
There's an option for this. Open your build job -> Repository -> Change "Clean" option to true.
That will do refresh the repo for every build

**Comment by bc3tech** [comment]
yup, that's actually selected - trying to do this is what's causing the `git clean -fdx` error I pointed out above...

**Comment by bryanmacfarlane** [comment]
It doesn't do the build against the old version of the source.  That's not correct.

Clean checkbox will do git clean -fdx and reset hard, then it will fetch the commit of the source from the build.  ~ line 119 here https://github.com/Microsoft/vso-agent/blob/master/src/agent/scm/git.ts 

So, checking clean means it will (1) discard anything not in the repo and reset the state back to what was in the repo and then (2) pull new source changes up to the commit the build is being run for.

there's another variable you can set on the definition which is build.clean=delete I believe.  But, I want to set the record state that what's being asserted is not true.

**Comment by bc3tech** [comment]
hm. well if it's not building against old i'm not sure how I could explain that we check a file in to `master`, tell it to build `master`, and what shows up on the build agent under `_work/#/s` of the build that's running is _not_ the version we checked in...

**Comment by bryanmacfarlane** [comment]
What version of the agent do you have ? (in package.json in the root of the agent).

The build summary should have the commit it built.

If you look at the build console, you will see exactly what commands we run live while we run it.  For example, I just kicked off a build to confirm.  Here's my console output:

```bash
git clean -fdx
Removing Tasks/ANT/anttask.js
...

git reset --hard HEAD
HEAD is now at 97477b5 delete old cocoa pods bash impl.  handler not supported anymore

git fetch origin

git checkout 97477b56ddd3ed79127f8421819f22a8af8cbf06
HEAD is now at 97477b5... delete old cocoa pods bash impl.  handler not supported anymore
```

I think look at the build at the end of the build and it has on the summary page:
Associated changes
    
Commit 97477b5 Authored by Bryan MacFarlane 
delete old cocoa pods bash impl.  handler not supported anymore

**Comment by bryanmacfarlane** [comment]
Still can't repro

https://github.com/Microsoft/vsts-agent
