### ISSUE TITLE
Doesn't handle Job Cancellation

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vso-agent#287]
Every time I cancel a build from the VSTS portal, the agent responds with

`Unknown Message Type: JobCancellation`

and then won't pick up any new builds until I stop and restart the agent.

**Comment by bryanmacfarlane** [comment]
The replacement for this agent supports cancellation. We are releasing a new preview tomorrow or early next week. It already has more features than this one

https://github.com/Microsoft/vsts-agent
