### ISSUE TITLE
Doesn't handle Agent Refresh

### ISSUE THREAD

**Issue by bc3tech** [Microsoft/vso-agent#288]
When issuing the "Update all agents in queue" command from VSTS control panel, an x-plat agent (on a Mac) will throw

`Unknown Message Type: AgentRefresh`

upon receiving the request.

**Comment by nigurr** [comment]
I guess you can't upgrade the x-plat agent from VSTS presently. This is coming in new CoreCLR Agent.

Presently, you have to upgrade from manually. Directions for the same available in https://github.com/Microsoft/vso-agent/blob/master/docs/onprem.md

**Comment by bryanmacfarlane** [comment]
The replacement for this agent will support updates.  We are releasing a new preview tomorrow or early next week.  It already has more features than this one

https://github.com/Microsoft/vsts-agent
