### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by cleverdude** [Microsoft/vso-agent#292]
Hi,
I just got unable to get local issuer certificate issue, when i tried to run tfs agent on linux. So, basically I am  trying to connect to TFS OnPrem server via https, from Red Hat Enterprise Linux Server release 6.4 machine.  I downloaded necessary root certificates for the authentication from tfs and added to /etc/pki/java/cacerts . Still, when i tried running run.sh, i still got the issue "unable to get local issuer certificate".

Following are the different things I have tried to get this working

* Added Root certitificate to /etc/pki/java/cacerts via keytool
* Copied Root certificate to /etc/ssl/certs
* Added an extra line in run.sh script which sets environment variable "CERT" to the correct certitificate

I got openssl to connect to tfs with this root certificate, by specifying extra openssl option "CAfile" pointing to this certiticate and it works fine.Which means the certificate I am getting is the correct one.So, it looks like when i run "./run.sh" command , it is looking at a different path to get the certificates for authentication and it is not getting the right one.

Can you help me with this please ? 

Many Thanks in Advance

**Comment by bryanmacfarlane** [comment]
We use node.  A quick search on node and this error revealed:

http://stackoverflow.com/questions/34809915/unable-to-get-issuer-certificate-unable-to-get-local-issuer-certificate

**Comment by bryanmacfarlane** [comment]
deprecated.  try the new agent @ https://github.com/Microsoft/vsts-agent/blob/master/README.md
