### ISSUE TITLE
Question about permissions

### ISSUE THREAD

**Issue by recordnotfound** [Microsoft/vso-agent#297]
When uploading custom summary (using build.uploadsummary or task.attachment), it is not visible to some people while it is visible to some other. What permissions determine if one can view it or not? Asked by @rovinbhandari on https://recordnotfound.com/vso-agent-Microsoft-14797

**Comment by bryanmacfarlane** [comment]
Not an agent issue.  Perhaps log an issue on task repo: vsts-tasks
