### ISSUE TITLE
VSO Agent | OAuth  issue 

### ISSUE THREAD

**Issue by SrinivasPithani** [Microsoft/vso-agent#298]
Hi,

I am using VSO agent (installed in CentOS Lx) inorder to build my code from VSTS environment. When I initiate a build, I get the following error in the console. I have never configured OAuth , how to get rid of this , is there any way that I can specify my agent to work with basic authentications (i.e. username/PAT ) . I have tried to change the VSO_GIT_USERNAME/PASSWORD variables but didnt help , can someone advice.

I can clone the git repo using the same usercredentials on test machines , so this is to say my PAT cred's are working fine., appreciate your advice.
```

cwd: /home/******Admin/******agent/_work
 valid scm providers: git,github,svn,tfsgit,tfsversioncontrol
Repository type: TfsGit
using source provider: tfsgit
loading: /home/******Admin/******agent/agent/scm/tfsgit
Using auth scheme: OAuth
running clean
 skipping clean since repo does not exist
getting code
https://************.visualstudio.com/DefaultCollection/******/_git/products
srcVersion: 02830b18779dd35bac74**
srcBranch: refs/heads/***-master
Using ref: 02830b18779dd35bac74**
/usr/bin/git arg: clone
/usr/bin/git arg: https://...@************.visualstudio.com/DefaultCollection/******/_git/products
/usr/bin/git arg: --progress
/usr/bin/git arg: s
exec tool: /usr/bin/git
Arguments:
clone
https://...@************.visualstudio.com/DefaultCollection/******/_git/products
--progress
s
Cloning into 's'...
fatal: Authentication failed for 'https://OAuth:********@************.visualstudio.com/DefaultCollection/******/_git/vehicles/'
rc:128
success:false
/usr/bin/git failed with return code: 128
```

**Comment by bryanmacfarlane** [comment]
Use this agent:

https://github.com/Microsoft/vsts-agent

Specifically, see: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/latebreaking.md
