### ISSUE TITLE
Shell Script task Working Directory other than root or folder script is in does not work

### ISSUE THREAD

**Issue by j0tt** [Microsoft/vso-agent#299]
I recently updated my agents only to find working directory does not appear to be working for my shell script tasks on my on-prem mac build agents.

Steps to reproduce:
Create a build with a Shell Script task
   - In advanced, specify a working directory.
Point the task to a .sh file with the contents "echo $PWD"

Observe in the build output the working directory is the directory the script resides in, not the directory specified in the task.

**Comment by bryanmacfarlane** [comment]
what's the version of your shellscript task (_work/tasks ...)  Also, what's the version of your agent?

**Comment by ericsciple** [comment]
Also what inputs (and exactly what values) are you specifying on the shellscript task?

**Comment by j0tt** [comment]
@bryanmacfarlane the shellscript task is using 2.0.0. I just updated the agents, VSO says Agent.Version = 1.999.0 but I'm dubious that is correct. Is there a better place to verify that?

@ericsciple generalizing as best I can: 
Script Path: dir/dir/script.sh
Working Directory: dir/dir/dir

**Comment by bryanmacfarlane** [comment]
Agent version is in package.json file in the root of the agent and it's reported as npm version in agent capabilities from the admin web UI.

**Comment by j0tt** [comment]
Agent.NpmVersion: 0.3.4

**Comment by bryanmacfarlane** [comment]
If the agent is updated, it should be 0.6.x

Trying to repro with 0.6.x

**Comment by j0tt** [comment]
Okay, I knew I updated them... VSO is reporting the wrong versions under Agent.NpmVersion. Interrogating the package.jason file I see 0.6.5 on all agents.

**Comment by bryanmacfarlane** [comment]
OK.  I got a repro and I have a fix.

If you want to confirm on your agent.  _work/tasks/ShellScript/2.0.0/shellscript.js
change line 21 from
```
        if (!tl.filePathSupplied('cwd')) {
```
to
```
        if (!tl.filePathSupplied('cwd')) {
```

**Comment by bryanmacfarlane** [comment]
Fixed in 4cf73301a50e49ce27b91350f0055e834cd26fe6

**Comment by bryanmacfarlane** [comment]
Fixed in https://github.com/Microsoft/vsts-tasks/commit/4cf73301a50e49ce27b91350f0055e834cd26fe6

**Comment by j0tt** [comment]
Awesome. Thanks for the quick turnaround!

**Comment by bryanmacfarlane** [comment]
np.  sorry for the inconvenience.
