### ISSUE TITLE
CmdLine task arguments not outputing empty strings ("")

### ISSUE THREAD

**Issue by j0tt** [Microsoft/vso-agent#300]
When specifying an argument to the command line task in the arguments form field, "" is being ignored:

Test Data
Tool: `curl`
Arguments: `http://www.google.com -d ""`

Expected console commend: `curl http://www.google.com -d ""`
Actual console command: `curl http://www.google.com -d`

Workaround: use single quotes.

Output Log (working folder scrubbed):
## [Debug] 2016-05-04T19:06:01.928Z:    -d

2016-05-04T19:06:01.928Z: [command]/usr/bin/curl http://www.google.com -d
2016-05-04T19:06:01.936Z: curl: option -d: requires parameter
2016-05-04T19:06:01.937Z: curl: try 'curl --help' or 'curl --manual' for more information

**Comment by bryanmacfarlane** [comment]
Will fix in new agent

**Comment by bryanmacfarlane** [comment]
Deprecated.  Replacement is here: https://github.com/Microsoft/vsts-agent
