### ISSUE TITLE
Agent not renewing lock on long iOS builds

### ISSUE THREAD

**Issue by j0tt** [Microsoft/vso-agent#304]
We recently introduced a change that impacted our build time significantly, the build takes about 70 minutes, With pre-processing (get sources, etc) it takes about 90. We are now experiencing agent issues. The build status page will say "build failed" but the xcode compile console output will still be running. It isn't until the compile finishes, that the agent stops working and the build goes full red.

The failed page then has this error:
`The job has been abandoned because agent iOSAgent did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.`

Interestingly, the the agent will pick up a new build while the "failed" build is still compiling (as evident by the console still outputting), so the agent will be running two builds in parallel.

Agent Version: `0.6.5`
ShellScript Task Version: `2.0.2`

I will share the _diag in a more private forum if needed.

**Comment by bryanmacfarlane** [comment]
This agent doesn't support cancellation.  The new one that is deprecating this one does: https://github.com/Microsoft/vsts-agent

**Comment by j0tt** [comment]
Well. I don't want the build to be canceled in the first place. I can't yet update to the new agent because the setup crashes when I try and input alternate credentials. We haven't moved to personal access tokens yet.

**Comment by bryanmacfarlane** [comment]
Yes, but in the event server abandons, it's all wasted work.  The way renewing the lock works is every 30 seconds, the agent renews the lock and if the server hasn't heard from the agent in 5 min+ (10 tries would have to fail), it assumes the worker has gone away (crashed etc...) and abandons the build.  Agent has an agent process (listener) and worker process for isolation and robustness.  If a worker crashes, this heals the agent from the servers point of view and starts taking jobs again.

So, key question is was there a > 5 minute stretch with networking issues?  Does it repro consistently with a long build? (longer build increases likelyhood).

Also, PAT token takes a minute to acquire ...  we will add basic auth option to new option soon

**Comment by j0tt** [comment]
No, there are no networking issues that I am aware of. It has been literally every build since the longer compile time was checked in.

I spun up a new agent using 2.99 on another machine. Comes with its own challenges, but I'll report back if this agent seems to be working better than the others.

**Comment by bryanmacfarlane** [comment]
OK.  In parallel, we could troubleshoot with Charles proxy.  But it might be easier if I give you a private with a few lines to output to the console around the renew logic.  What's wierd is if the renew logic was completely busted, build would fail in about 5 min.  Does it always fail around the same time.

Ahhh - one other thing to check.  On the general tab of the definition, there's a build timeout and it defaults to 60.  That should be 2 - 3 X bigger than the longest time you expect.  That's there in case a build deadlocks and hangs (unit test etc...).  Server will send cancellation and free up the agent.

**Comment by bryanmacfarlane** [comment]
... and 0 is infinite but that has a big downside.  I recommend 2x

**Comment by j0tt** [comment]
It fails around the 80 to 90 minute mark. Though, I guess I can't say that with confidence if the failure is happening earlier but the lack of cancellation shows the compiler still running.

I set the timeout to 0 after increasing it from 60 to 90 to 120 :/ Should I put put it back to the ~150 mark?

**Comment by bryanmacfarlane** [comment]
0 is fine for now while you're troubleshooting.  See if it makes a difference.  Tonight or tomorrow, I will send you a private of a file to replace with some extra outputs to the console around the renew code.

Are you running as a svc or interactive?  What version?

**Comment by j0tt** [comment]
As a service. The agent version is 0.6.5, is there another version you're looking for?

**Comment by bryanmacfarlane** [comment]
nope - just wanted to know which version to based my patch I give you

Also, if you can specify your account name ___.vs.com (if hosted) then we can look if exceptions in service around renewing the lock (timeouts etc...).  If not, you can always email me - bryanmac and I'm at microsoft email

**Comment by bryanmacfarlane** [comment]
Fixed in the replacement agent.  Just dropped 1.101.0 yesterday
https://github.com/Microsoft/vsts-agent
