### ISSUE TITLE
The .tar.gz files on release page are actually plain .tar, not .tar.gz

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vso-agent#306]
As per title, the file names are incorrect.

For example this: https://github.com/Microsoft/vso-agent/releases/download/0.6.5/xplat0.6.5Linux64.tar.gz

When running `tar -zxvf xplat0.6.5Linux64.tar.gz` it complains with

> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

Treating this as plain `.tar` works.

Also looking at the sizes, here is the original and here is the one compressed:

```
30M May 13 19:42 xplat0.6.5Linux64.realtar.gz
67M Apr 21 01:33 xplat0.6.5Linux64.tar.gz
```

Not sure if anyone can fix this or if it's actually important :)

**Comment by bryanmacfarlane** [comment]
Of course it's important :) 

That said, you should look to the replacement for this agent.  It's about to deprecated and the replacement is farther along:  https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
This is fixed in the agent replacing this one:
https://github.com/Microsoft/vsts-agent
