### ISSUE TITLE
Release 'Publish Build Artifacts' fails with 'Unable to find container for build'

### ISSUE THREAD

**Issue by sabiori** [Microsoft/vso-agent#308]
Hi, I am trying to publish some test results from the release agent working folder using the task 'Publish Build Artifacts' that I put into my release definition, but it fails with:
##[error]Unable to find container for build: 88

I think 88 is the id of the build that triggered the release.

Interestingly, I have another 'Publish Build Artifacts' in my build definition and that works just fine.

Here is the task setup from my release definition
![image](https://cloud.githubusercontent.com/assets/19437249/15373889/9c929e84-1d3f-11e6-9799-b9ea57103b79.png)

And this is all the log output of the task:
   Set workingFolder to default: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30 
   ##[debug]loading inputs and endpoints 
   ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION 
   ##[debug]loading INPUT_ARTIFACTNAME 
   ##[debug]loading INPUT_ARTIFACTTYPE 
   ##[debug]loading INPUT_PATHTOPUBLISH 
   ##[debug]loading INPUT_TARGETPATH
   ##[debug]loaded 5
   ##[debug]check path : C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30\task.json 
   ##[debug]set resource file to: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30\task.json 
   ##[debug]system.culture=en-US 
   ##[debug]PathtoPublish=C:\a\1196b1921\requirementsCoverage.html 
   ##[debug]check path : C:\a\1196b1921\requirementsCoverage.html 
   ##[debug]ArtifactName=ReqirementCoverage 
   ##[debug]ArtifactType=Container 
   ##[debug]TargetPath=\\my\share\waverage.feature\waverage_plan_in_traderwebapp_2016_05_18.5 
   ##[error]Unable to find container for build: 88

Could you help me find out what the problem is? 

Or in case this task is not supported in a release definition, is there a way around this? Something like using cUrl or powershell to attach the files to the release using the VSO Rest API?

**Comment by bryanmacfarlane** [comment]
The output from above is not from this agent that is in this repo.  Please log your issue in the tasks repo
https://github.com/Microsoft/vsts-tasks
