### ISSUE TITLE
Enable non interactive configuration and run

### ISSUE THREAD

**Issue by giggio** [Microsoft/vso-agent#309]
Right now the only way to configure and to run the agent is interactively, with a human interacting with the console.
We need to be able to configure the agent by passing command line arguments.
We also need to be able to run the agent by passing command line arguments. Or it should simply remember the user name and password from the initial configuration.
The use of environment variables should also be allowed, so, for instance, if a variable, say, `AGENT_USER` is set, you should use it (of course you would name such variables), and configuration and run should work without human interaction.

**Comment by bryanmacfarlane** [comment]
You can run as a service on OSX (plist) and Linux (init.d, systemd)
We offer a convenience to create the plist on OSX: https://github.com/Microsoft/vso-agent/blob/master/docs/service.md

The host takes -u and -p command line arguments. 

All that said, you should be using the new agent that is replacing this one.  This one is deprecated:
https://github.com/Microsoft/vsts-agent

**Comment by giggio** [comment]
Opened https://github.com/Microsoft/vsts-agent/issues/221, same problem exists with the new agent. At lease it already runs without user interaction.
