### ISSUE TITLE
Gitrepo.ts tries to create directory when it already exists

### ISSUE THREAD

**Issue by Ricky-N** [Microsoft/vso-agent#31]
existsSync is deprecated, and it seems the repoDirName passed in here has some environment variables that aren't being expanded properly or something along those lines. Should probably switch to accessSync() and make sure to not take environment variables for granted as node interacts with file system directly. 

2015-06-19T18:56:24.1590665Z ##[error]Failed to make directory 'C:/users/spcusage/Build': Cannot create a file when that file already exists.

    if (!fs.existsSync (repoDirName)) {
        ctx.info('Creating repo dir: ' + repoDirName)
        shell.mkdir('-p', repoDirName);
        …

**Comment by bryanmacfarlane** [comment]
We rewrote git provider recently.  I also see you're running on windows and right now, it's not supported on windows.  shell.mkdir -p should be passive.  At least it is on *nix
