### ISSUE TITLE
raspberry3 

### ISSUE THREAD

**Issue by ThomasKue** [Microsoft/vso-agent#313]
How do i solve this:

bxxxxx@rpi3-yyyy:~/myagent $ curl -skSL https://aka.ms/xplatagent | bash

Platform: Linux

--------------------------------------
     Acquiring Node 5.6.0
--------------------------------------

Downloading Node 5.6.0 @ https://nodejs.org/dist/v5.6.0/node-v5.6.0-linux-x86.tar.gz
Setting internal node in path
using node : /home/bxxxxx/myagent/runtime/node/bin/node
using npm  : /home/bxxxxx/myagent/runtime/node/bin/npm

--------------------------------------
     Acquiring TEE CLI 14.0.2-private
--------------------------------------

Downloading  TEE CLI 14.0.2-private
Accepting Eula (/home/bxxxxx/myagent/runtime/tee/tf)
bash: line 163: Error: command not found

--------------------------------------
     Installing agent installer
--------------------------------------

Cleaning up existing agent
~/myagent/_installer ~/myagent
Installing...
script location: .
installing vsoagent-installer@0.6 ...
Failed: npm install Failed with return code 2

**Comment by nigurr** [comment]
This is deprecated. Please use https://github.com/Microsoft/vsts-agent

**Comment by ThomasKue** [comment]
There are no armHF (raspberry 3) version!

**Comment by nigurr** [comment]
you can always build from source. But I doubt about dotnet support for raspberry

**Comment by ThomasKue** [comment]
Yes, coreclr is not supported on armHF! - so please help me and solve this issue. git and gulp runs.

**Comment by ThomasKue** [comment]
node and npm also.

**Comment by bryanmacfarlane** [comment]
One way to solve it is go to the releases hub on github project.  We distribute fully realized tar.gz files.  That sh script is a way to realize it on demand.

Regarding support: yes we know core clr isn't quite as broad as node was at them moment.  But it was not enough of a reason to still have two agents (many more downsides to that).  If you need to automate something on a rasberry, you can run an agent and remote ssh commands to the rasberry.  I believe this sprint adds an ssh task to even make that easier

**Comment by ThomasKue** [comment]
thank you, then i go the ssh way.
