### ISSUE TITLE
Access Denied while trying to start the Agent. macOS VM

### ISSUE THREAD

**Issue by vdangwal** [Microsoft/vso-agent#316]
Agent Started.
##[Error] 2016-08-10T17:19:23.834Z: Message Queue Error:
##[Error] 2016-08-10T17:19:23.834Z: Could not create an agent session. Retrying in 15 sec
##[Error] 2016-08-10T17:19:23.834Z: Message Queue Error:
##[Error] 2016-08-10T17:19:23.834Z: Failed Request: Forbidden(403) - Access denied. Digital Solutions needs Listen permissions for pool Default to perform the action. For more information, contact the Team Foundation Server administrator.

Could anyone please help? this is on premises Mac VM using VMWare.

We have given all the required permissions to this Group Id but still not working.

**Comment by bryanmacfarlane** [comment]
The template asked for things like version and diag dumps.  Can you create from template or supply all that info?

**Comment by vdangwal** [comment]
[diag.zip](https://github.com/Microsoft/vso-agent/files/411816/diag.zip)
Version of Mac: El Captain 10.11.6

Sorry if you were talking about some other version :)

**Comment by bryanmacfarlane** [comment]
I'm asking about the version of the agent.  It shows up in the admin UI for the agent in the queue/pool tab.

**Comment by bryanmacfarlane** [comment]
I see the confusion.  This agent is deprecated.

Use this one.

http://github.com/microsoft/vsts-agent

**Comment by vdangwal** [comment]
Thanks for the Update. I was using vsts-agent-osx.10.11-x64-2.104.**1**.tar.gz . This is what i got online from VSTS website earlier when downloading Agent.  The latest release i saw is vsts-agent-osx.10.11-x64-2.104.**2.**tar.gz

**Comment by ericsciple** [comment]
If it doesn't work with 2.104.2, please open an issue in the repo http://github.com/microsoft/vsts-agent

This repo "vso-agent" is for an older version of the agent. It looks like the logs you attached are from the old agent. Can you try extracting 2.104.2 to a new directory to make sure the files aren't mixed.

**Comment by bryanmacfarlane** [comment]
The diag log you seems to be from this vso-agent (not the vsts-agent).

Use the vsts-agent.  The docs in vsts-agent also say to create a new dir and unzip into it.  The new agent

**Comment by vdangwal** [comment]
Sure. I am going to use .2 version but i was using vsts-agent .1 version for sure :). Not sure why diag log shows vso-agent logs.

**Comment by vdangwal** [comment]
.2 version worked. I think .1 should also have work. As i was missing openssl dependency on my mac. once i installed it, it worked. And good to see you guys using .Net Core on mac :). Please close the issue.
