### ISSUE TITLE
Build sources directory is not cleaned if it contains other Git repositories

### ISSUE THREAD

**Issue by michael-baker** [Microsoft/vso-agent#324]
In my setup I have a TFS 2017 build definition pointing at a Git repository.

![image](https://user-images.githubusercontent.com/1083622/27816489-fa73ea78-60df-11e7-85d8-7a17d3e2a1a9.png)

During the build execution other Git repositories are fetched and dropped into the Build.SourcesDirectory via custom scripts.

The next time I queue a build it will fail as the source directory is not cleaned as "git clean -fdx" is not enough. As my sources directory contains other .git folders the clean command needs to be "git clean -ffdx" to really really force the clean to occur.

Example:

```
C:\agent\_work\4\s>git clean -fdx
Skipping repository Foo/
Skipping repository Bar/
Skipping repository Baz/
Skipping repository _BUILD_215248575/
```

```
C:\agent\_work\4\s>git clean -ffdx
Removing Foo/
Removing Bar/
Removing Baz/
Removing _BUILD_215248575/

```

**Comment by bryanmacfarlane** [comment]
Deprecated.  Replacement is here: https://github.com/Microsoft/vsts-agent
