### ISSUE TITLE
No support for Red Hat Enterprise Linux 6.7 in the new agent

### ISSUE THREAD

**Issue by o11eman** [Microsoft/vso-agent#327]
We have been using this agents for builds targeting RHEL 6.7. The new .NET Core agent is not supported on that version. What is your suggested solution? We do not see an update to RHEL 7.x in the near future and needs to maintain our software with new builds.

**Comment by randallcara** [comment]
i

**Comment by bryanmacfarlane** [comment]
The net core one should support a broader range of red hat and linux support.  Try latest version again
