### ISSUE TITLE
Task Group: Step with "Always Run" does not run if previous step fails

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/vso-agent#329]
We have one task group, it could always run when build fail.
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_taskgroups?_a=properties&taskGroupId=2ba41946-8425-454f-865a-dd5366fa4acb
 
When I include it in release.
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=44549&definitionId=443&_a=release-logs
It is skipped, it is expected behavior?
Could you take a look if there is LSR happened?
 

Here is a simplified example:
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_release?definitionId=740&_a=release-summary&releaseId=44561&source=ReleaseExplorer
with always run option.
Trigger ICM is skipped.

**Comment by GuofuZhong** [comment]
I have found that re-create this task group. It will work. (but in task group, always run isn’t selected.)
This is latest VSO break the backward compatible.

Thanks,
Guofu

**Comment by bryanmacfarlane** [comment]
vso-agent is deprecated.  Create issue in the vsts-tasks repo
