### ISSUE TITLE
.lock file isn't removed on restart (OSX 10.10.3)

### ISSUE THREAD

**Issue by jeyoor** [Microsoft/vso-agent#33]
Summary
----

After rebooting OSX 10.10.3, I'm getting an error message on service startup

    cat /Users/username/Library/Logs/vsoagent.poolname.hostname/stderr.log
    2015-06-22T15:32:44.516Z: Another agent process is running.  Exiting.

After removing the .lock file manually, the agent comes up on next restart.

Please pardon my frivolous issue if this is already planned to be addressed. I wasn't sure if [this TODO](https://github.com/Microsoft/vso-agent/blob/master/src/agent/service.ts#L84) in service.ts applied to this issue or was referencing something else...

Thanks,
Jeyan

Details
----
installed service via

    ./svc.sh install

service was shown as running

    ps -ef | grep node

restarted Mac Mini running OSX 10.10.3

    sudo shutdown -r now

service wasn't started

    ps -ef | grep node

Log file showed error message
    
    cat /Users/username/Library/Logs/vsoagent.poolname.hostname/stderr.log
    2015-06-22T15:32:44.516Z: Another agent process is running.  Exiting.

Removed lock file & restarted

    rm /path/to/installed/agent/.lock
    sudo shutdown -r now

service was started

    ps -ef | grep node

**Comment by bryanmacfarlane** [comment]
this is fixed.  I removed the lock file concept.  there is a .pid file now but not the same purpose
