### ISSUE TITLE
##[Error] Failed with Error Output

### ISSUE THREAD

**Issue by ThomasKue** [Microsoft/vso-agent#34]
Hallo, how could i ignore this error? bash script run's, but vsoagent tells me orange not green!

******************************************************************************
 Running ShellScript
******************************************************************************
running: bash /xxxxx/copynas.bash anynodemon-1.15.1 > out.log 2> /dev/null
##[Error] Domain=[YYY] OS=[Unix] Server=[Samba 3.6.24]
##[Error] 
##[Error] putting file zzzzzzzzzzz-1.15.1-debian8-x64-release.deb as \cds\anynode\debian\zzzzzzzzzzz-1.15.1-debian8-x64-release.deb (12778.9 kb/s) (average 12778.9 kb/s)
##[Error] 
##[Error] Failed with Error Output

**Comment by bryanmacfarlane** [comment]
With the latest shell script task, there should be an advanced option whether to fail on stderr out.

You can also pipe stderr to stdout for any calls in a shellscript:
do_something 2>&1
