### ISSUE TITLE
HTTP 403 Error with vso-agent and VSO account

### ISSUE THREAD

**Issue by smflorentino** [Microsoft/vso-agent#37]
I'm currently using a free VSO account I've successfully configured 2 Windows agents using Alternate Credentials. However, on Linux, I can create the agent and it shows up in VSO, but it cannot start. Any ideas why it would work on Windows but not Linux? Is it because Alternate credentials are deprecated? 
![image](https://cloud.githubusercontent.com/assets/3495150/8344579/449984ea-1a98-11e5-9764-faaf85681cf8.png)

**Comment by jeyoor** [comment]
You might try
    1. Making sure you are using the "alternate credentials" you created in Visual Studio Online
    1. Ensuring that the account being used is added as both a service account and a pool administrator for that pool in Visual Studio Online
Full details:
[readme](https://github.com/Microsoft/vso-agent/blob/master/README.md)
[video walkthrough](https://www.youtube.com/watch?v=_snVbL39kyU&feature=youtu.be)

**Comment by smflorentino** [comment]
I'm sorry! I didn't realize the configuration for the cross-platform agent was slightly different than the Windows agent (The account was part of Agent Pool Administrators, but not Service Accounts). That explains why it worked on Windows but not on Linux.

Thanks you again!
