### ISSUE TITLE
Git repo with on-premise TFS

### ISSUE THREAD

**Issue by jmezach** [Microsoft/vso-agent#38]
I've set up the xplat agent on a Mac Mini server and succesfully connected it to my on-premise TFS. However, when I run a build that is using a Git repo (TFS hosted Git that is) I'm getting the following output:

```
preparing Workspace
cwd: /Users/Shared/BuildAgents/Agent1/_work/build/8f606dfb41c4926101422d0198a9c955169bafb520042a138beeaec27c5ce25f
srcVersion: 8ed6808d0ef4b950182ffb3c6513dbd87fc2c1df
srcBranch: refs/heads/master
selectedRef: 8ed6808d0ef4b950182ffb3c6513dbd87fc2c1df
Using auth scheme: OAuth
Repo: http://zeustfs02:8080/tfs/DefaultCollection/WMS%20Git/_git/DeVries.WMS.Analytics
Repo path: /Users/Shared/BuildAgents/Agent1/_work/build/8f606dfb41c4926101422d0198a9c955169bafb520042a138beeaec27c5ce25f/repo
Using ref: 8ed6808d0ef4b950182ffb3c6513dbd87fc2c1df
repo location:http://zeustfs02:8080/tfs/DefaultCollection/WMS%20Git/_git/DeVries.WMS.Analytics
cwd: /Users/Shared/BuildAgents/Agent1/_work/build/8f606dfb41c4926101422d0198a9c955169bafb520042a138beeaec27c5ce25f
running: git --version
git version 2.3.2 (Apple Git-55)
 
+++++++Git clone http://zeustfs02:8080/tfs/DefaultCollection/WMS%20Git/_git/DeVries.WMS.Analytics 
Cloning into folder: repo
running: git clone --progress http://zeustfs02:8080/tfs/DefaultCollection/WMS%20Git/_git/DeVries.WMS.Analytics repo
Cloning into 'repo'...
fatal: Authentication failed for 'http://zeustfs02:8080/tfs/DefaultCollection/WMS%20Git/_git/DeVries.WMS.Analytics/'
```
Seems that it is unable to authenticate to my TFS server. Is this unsupported?

**Comment by jmezach** [comment]
I've managed to get this to work by manually cloning the repository on the build agent and making sure that git stored the credentials in the OSX keychain. I guess that's good enough for now, but it would be nice it it could just use the credentials I've already provided when I ran the agent.

**Comment by chrisrpatterson** [comment]
This is a general issue we are working on with respect to OSX. Apple includes the osxkeychain cred helper with their git implementation and it always gets called regardless of what we pass on the command line.

**Comment by bryanmacfarlane** [comment]
We actually do implement a cred helper (and askpass) and do supply the creds passed down from the server.  But, apple (and some others) put a plug-in in git-core directory so it's always run and runs ahead of asking us.

>> but it would be nice it it could just use the credentials I've already provided when I ran the agent.

Note that when this gets worked out, it's not your creds - those are just creds to connect to the queue.  Our build server generates an oauth token on demand that's time bombed and passed down with the job request to the agent.  This is how the scope on the general tab works.  And this is the problem with the keychain caching and getting in front of us - it's cached and it may be an expired token when it runs again.  

We're working on a solution where we always use the oauth token when working with the server (clone, push, etc...)

**Comment by bryanmacfarlane** [comment]
This is fixed.  the latest 0.2.26 agent and beyond uses the OAuth generated token regardless of what your run the agent as
