### ISSUE TITLE
Running PublishBuildArtifacts on Linux results in error

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/vso-agent#43]
I am trying to utilize the PublishBuildArtifacts task within a build definition that is designed to build some artifacts within a Linux environment.

1 2015-07-22T20:42:57.498Z: Cleaning staging folder: /home/msimons/BuildAgents/MultiDevTest/_work/build/ce2c019942eac2ab3e1bceb308a15a1f1789b1e89e2218e12a6aecbde54b4869/staging/CoreClr
2 2015-07-22T20:43:00.109Z: found 25 files
3 ##[Error] 2015-07-22T20:43:00.305Z: TypeError: undefined is not a function
4 ##[Error] 2015-07-22T20:43:00.389Z: Return code: 1

The inputs I have set are the following
Copy Root = ""
Contents = "bin/Product/**"
Artifact Name = "CoreClr"
Artifact Type = "Server"

I have also tried to user the File share type with the same result.  My expected outcome would be for this to work or to have more assistance from the log output in determining the source of the failure.

**Comment by MichaelSimons** [comment]
Opened issue in wrong repo

**Comment by bryanmacfarlane** [comment]
even though closed - on the build definition variables tab, set
system.debug to true

that should output many more details
