### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vso-agent#55]
```
/Users/ticino/Desktop/joao/vsobuild/node_modules/vso-task-lib/lib/toolrunner.js:48
for (var i = 0; i < args.length; i++) {
^
TypeError: Cannot read property 'length' of null
at ToolRunner._argStringToArray (/Users/ticino/Desktop/joao/vsobuild/node_modules/vso-task-lib/lib/toolrunner.js:48:33)
at ToolRunner.arg (/Users/ticino/Desktop/joao/vsobuild/node_modules/vso-task-lib/lib/toolrunner.js:60:47)
at Object.<anonymous> (/Users/ticino/Desktop/joao/vsobuild/_work/tasks/ShellScript/1.0.9/shellscript2.js:9:6)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3
Return code: 1
```

It happens when executing a shell script in a build definition.

**Comment by joaomoreno** [comment]
It happens in a Shell Script step. I could only fix it by adding a fake argument in the **Arguments** field of that step.

My TFS server seems to have been updated very recently, which may be the cause for this.

**Comment by bryanmacfarlane** [comment]
I'm investigating.  Someone else said the workaround was to set in the definition task arguments value to ""

**Comment by bryanmacfarlane** [comment]
Can you go into your agent the root of your agent and type `npm list`?

What version is vso-task-lib?
├─┬ vso-task-lib@0.4.4

**Comment by bryanmacfarlane** [comment]
I believe this was fixed a few weeks ago in vso-task-lib 0.4.2 (current is 0.4.4)

https://github.com/Microsoft/vso-task-lib/commit/84bd01430ced82fde2256d899c4642dc056c4aa6 

To be sure, go into the root of your agent and run npm list.  If it's less than 0.4.2, you can run npm update in the root of the agent (where the package.json is)

├─┬ vso-task-lib@0.4.4

If it's >= 0.4.2, then let me know.

I'm going to also change updating the agent to also run npm update since the task-lib can linger back.

**Comment by joaomoreno** [comment]
I have `vso-task-lib@0.3.5`. Ran `npm update`. Still have `0.3.5`. This happens due to the `package.json` located sibling to the `agent` folder.

Just deleted my whole agent, reinstalled the `vsoagent-installer` and created a new agent. Now I get `vso-task-lib@0.3.5`.

**Comment by bryanmacfarlane** [comment]
Did you follow the "Update Existing Agents" instructions from the readme?  Both steps?  -g on the first step?

The currently release agent from npm (0.2.26) has a package json with ^0.4.0 of vso-task-lib

I see this:

~/$ sudo npm install vsoagent-installer -g
Password:
/usr/local/bin/vsoagent-installer -> /usr/local/lib/node_modules/vsoagent-installer/bin/install.js
vsoagent-installer@0.2.26 /usr/local/lib/node_modules/vsoagent-installer
├── iniparser@1.0.5
...
├── vso-task-lib@0.4.4 (shelljs@0.3.0)
...
└── svcinstall@0.2.1 (shelljs@0.3.0, plist@1.1.0)

**Comment by joaomoreno** [comment]
I updated it two weeks ago. Unfortunately I don't recall what were the exact commands... I'll keep an eye out next time I try to update it.

**Comment by bryanmacfarlane** [comment]
OK - thx.  

I'll close for now since I confirmed it's fixed.  Reactivate or let me know if you have issues
