### ISSUE TITLE
Invalid URL error when using non-FQDN hosts

### ISSUE THREAD

**Issue by DanielBMann9000** [Microsoft/vso-agent#56]
As an example:

> ictfs-admin@IC-TFS-BA-02Lin:/usr/vsoagent$ node agent/vsoagent
> Enter alternate username > tfs-build@azure.incyclesoftware.com
> Enter alternate password >
> Enter server url > http://ic-tfs-at-01:8080/tfs
> Enter agent name (enter sets IC-TFS-BA-02Lin)  >
> Enter agent pool name (enter sets default)  >
> Error starting the agent
> http://ic-tfs-at-01:8080/tfs is not a valid URL

"ic-tfs-at-01" is not a FQDN. This is caused by line 184 of configuration.ts:
`throwIf(!check.isURL(settings.serverUrl), settings.serverUrl + ' is not a valid URL');`

The validator library has options for controlling this behavior.

**Comment by bryanmacfarlane** [comment]
I believe we accepted a PR for this.  It's fixed now right?

**Comment by DanielBMann9000** [comment]
Correct. I found the source of the issue and opened the issue, then thought
"Wait a minute, this is on Github, I might as well just fix it myself and
send a PR." :)
