### ISSUE TITLE
Starting vsoagent interactively yields connect ECONNREFUSED without sending SYN..

### ISSUE THREAD

**Issue by RuudHbm** [Microsoft/vso-agent#61]
Fresh install of Xubuntu 14.04.3 on physical machine.
Followed the README.md literally.
installed curl, nodejs (v0.12.7) and npm (2.11.3).
Used FQDN of Team Foundation Server to startup agent, but it exits with:

Error starting the agent
connect ECONNREFUSED.

Connecting with Firefox to the same server with identical credentials works OK.
Installed Wireshark; shows connection between Firefox and TFS. Shutdown firefox, start vsoagent: no packet shown in Wireshark (no SYN sent....)

What am I doing wrong?
What can I do to debug this?

**Comment by bryanmacfarlane** [comment]
Is this on-prem TFS or VSO?
What URL are you using?
Can you open the tfs url in a browser from the Ubuntu box?
Any proxies involved?
Ensure IPSec domain.

I recorded a video on how to get an http trace using charles proxy:
https://www.youtube.com/watch?v=PAVG50t_1bw

**Comment by RuudHbm** [comment]
Its an on-prem TFS.
I use the URL <mytfsserver>:8080/tfs where <mytfsserver> is the FQDN of the on-prem TFS.
I can use Firefox on the ubuntu box to connect to <mytfsserver>:8080/tfs without any problem. No http proxies are involved. Wireshark on the Ubuntu box shows the TCP connection between firefox and mytfsserver. Wireshark also shows that node agent/vsoagent.js does absolutely nothing on the network (no attempt to connect to mytfsserver).
I will attempt to install charles proxy for Debian...

**Comment by RuudHbm** [comment]
Nice: I wrote the URLs in such way that it got snipped...
The url is like mytfserver.mydomain.com:8080/tfs

**Comment by bryanmacfarlane** [comment]
OK - confused - is it working?  By snipped, does it mean you left off the protocol

**Comment by RuudHbm** [comment]
Got it working!
The URL entered for the vsoagent needs the protocol (http:) and a FQDN of the server e.g.:
http://mytfs.mydomain.com:8080/tfs
We also needed to enable Basic Auth on the TFS as described in http://blogs.teamfoundation.co.za/2015/05/installing-and-configuring-tfs-2015-on.html

**Comment by bryanmacfarlane** [comment]
Great.  I'm going to re-open and say we should have better error message here.  Shouldn't have to resort to tracing for improper url - we should tell you

**Comment by bryanmacfarlane** [comment]
I'll fix soon

**Comment by bryanmacfarlane** [comment]
Since we're hot on the new agent and the issue was addressed by using FQDN, closing this
