### ISSUE TITLE
TFS build fails due to long pathname used while getting sources from repo

### ISSUE THREAD

**Issue by RuudHbm** [Microsoft/vso-agent#65]
The build on my vsoagent (on Linux) fails due to a tf error while getting the sources:

/home/lnxbld/myagent/_work/build/49a59345fbf5ecea51a2a59c98b55ff13a318a565bf31a0ea33ae974b6180524/repo/$/Perception/Main/Embedded/Plaza/Projects/Vx_Genesis_Minimum_DigMod1M:
Getting .tfignore
Getting Genesis_Minimum_DigMod1M.wpj
Getting linkSyms.c
An error occurred: com.microsoft.tfs.core.exceptions.TECoreException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

Mmmh: Linux supports long pathnames, Windows doesn't....
Why use a 64-char hash as path element?
By-the-way: Linux does not like the $ within the path.

**Comment by bryanmacfarlane** [comment]
I'm getting rid of the hash in the path.  The hash is used so if someone changes the repo, the url etc... on the definition, the agent gets a new working directory.  Keeping the hash but changing it store in a map file to a # folder name.

**Comment by RuudHbm** [comment]
Hi Bryan,

Can you get rid of the $ in the path also (agent/_work/build/hash/repo/$/), various *nix tools break on that.

Regards,
Ruud

**Comment by yacaovsnc** [comment]
The latest code in master should compute the common path segments for all the mappings, and only map from the unique segments.  Since "$" is virtually on all mappings thus is a common path segment, it will be removed in the final mappings.

**Comment by bryanmacfarlane** [comment]
should be address now with latest @ preview agent

**Comment by Micahel55** [comment]
Best way to resolve the issue will be using LongPathTool Software
