### ISSUE TITLE
Configuration of agent fails behind proxy

### ISSUE THREAD

**Issue by gkl2** [Microsoft/vso-agent#67]
registration of build agent fails with HTTP/1.1 400 Bad Request returned from proxy.
Not sure if request should include :443 for https requests.
currently request looks like this
GET https://apps-munichre.visualstudio.com/_apis/connectionData HTTP/1.1\r\n

but should be
CONNECT https://apps-munichre.visualstudio.com:443 HTTP/1.1\r\n
and doing some SLL handshake.

**Comment by bryanmacfarlane** [comment]
Agent supports a proxy environment variable

export HTTP_PROXY=<proxy url>

Note that it was primarily put in place for debugging.  See: https://www.youtube.com/watch?v=Ta2c3sUbJ18

Also note that you will likely need to set git config global settings to use a proxy
