### ISSUE TITLE
On premise TFS Git OAuth clone failed on agent 

### ISSUE THREAD

**Issue by cybnetsurfe3011** [Microsoft/vso-agent#68]
I get the following error when trying to run the xplat agent.
The agent is running on an updated Arch Linux box.
The agent can connect to the pool just fine.
My server has Basic auth and Windows auth enabled.
To check permissions, I had the agent connect using the server administrator account and it still got the error.

******************************************************************************
Preparing tasks
******************************************************************************
******************************************************************************
Running prepareWorkspace
******************************************************************************
preparing Workspace
cwd: /home/buildbot/_work/build/5e4d9fa0a08108dca09c3c958f6ffb51db2ab6879a225bb61bf84d22f55efd33
using source provider: tfsgit
loading: /home/buildbot/agent/scm/tfsgit
Using auth scheme: OAuth
running clean
 skipping clean since repo does not exist
getting code
https://[server]:8080/tfs/[collection]/_git/[project]
srcVersion: 4bf89e336e69194e927dc078af9281d77683c7b3
srcBranch: refs/heads/dev
Using ref: 4bf89e336e69194e927dc078af9281d77683c7b3
/usr/bin/git arg: clone
/usr/bin/git arg: https://...@[server]:8080/tfs/[collection]/_git/[project]
/usr/bin/git arg: --progress
/usr/bin/git arg: repo
exec tool: /usr/bin/git
Arguments:
clone
https://...@[server]:8080/tfs/[collection]/_git/[project]
--progress
repo
Cloning into 'repo'...
fatal: Authentication failed for 'https://OAuth:eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjN2Yjd3emNuY3dJZVRYclgzRFF2N3lOUjEyVSJ9.eyJuYW1laWQiOiI0Y2Q2MGZkZi1jN2I4LTQyZmUtYWRkOS0yNmQ1NTM4YzQ4ZTYiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiI1NzYwYWRlOS04NjZmLTRhZTAtYmExZi0wOTk4NDhjNGEzOTEiLCJpc3MiOiJkZXYuZGltZW5zaW9uYWxwaGEubmV0IiwiYXVkIjoiZGV2LmRpbWVuc2lvbmFscGhhLm5ldCIsIm5iZiI6MTQ0MDI2NDk1NSwiZXhwIjoxNDQwMjY4ODU1fQ.NSKfQiQWN8kMEQMxvI0uuzdOhDlfzbsoPMVJp0DHY33h1XkMDu1DwwKlclR-rIYy5n5-5rME1pXp7vuLtT73NjrTL7ghTLnmF...
rc:128
success:false
/usr/bin/git failed with return code: 128

**Comment by bryanmacfarlane** [comment]
try setting envvar 

VSO_GIT_USERNAME
VSO_GIT_PASSWORD

https://github.com/Microsoft/vso-agent/blob/master/src/agent/scm/tfsgit.ts

**Comment by bryanmacfarlane** [comment]
I will change it soon so you can use a secret var on the definition a well.  Assigning to me.

**Comment by insanity13** [comment]
I've got the same error 
"Cloning into 'repo'...
fatal: Authentication failed for 'http://OAuth:eyJ0e"

Trying to set envvar via:
export VSO_GIT_USERNAME=user
export VSO_GIT_PASSWORD=pass

But it does not helps.

**Comment by andyedinborough** [comment]
Setting those environment variables worked for me.

**Comment by bryanmacfarlane** [comment]
We just made it so you don't have to set those variables.

See latest docs.  Use latest @preview version.  Set force basic to true during configuration.

That allows the agent to use the basic creds used for listening to the queue for git operations (instead of the oauth token which doesn't work on prem)
