### ISSUE TITLE
Issue with Azure Storage Emulator, VSO and Integration Tests

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vso-agent#72]
Firstly please accept my apologies if this is not the right place to ask this question...

We have some integration tests that relies on Azure Storage Emulator which fail when we run them using VSO Build with the following:

-------- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it 127.0.0.1:10002

These test for fine on our local machine(s). I'm suspecting that it's something to do with loopback adapter or such like as I've had problems like this before with server's which have been hardened as I assume the environment hosting VSO build agent's are.

Does anyone have any ideas on how I could run the Azure Storage Emulator successfully using hosted VSO agent ?

**Comment by chrisrpatterson** [comment]
We don't support running the azure storage emulator on the hosted build agent. It requires higher privileges than what we allow for the buildguest on those machines.

Sent from my Windows Phone
________________________________

**Comment by johnkattenhorn** [comment]
@chrisrpatterson - Thanks for confirming, I suspected as much and its understandable. I'll build out a VM with a build agent on it and run them from there.

**Comment by gmetzger** [comment]
@chrisrpatterson Just wondering if VSTS build agents still block Azure Storage Emulator? I'm trying to run automated tests in VSTS using Azure storage emulator without setting up a separate build server.
