### ISSUE TITLE
Attempting to test the TFSVC support on master for on-premises TFS gives OAuth error

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vso-agent#73]
Please let me know what I'm missing to enable the TF client to get the source down to our build server.
Below is the output I get using the TFSVC support on master at the present time.

******************************************************************************
Preparing tasks
******************************************************************************
******************************************************************************
Running prepareWorkspace
******************************************************************************
preparing Workspace
cwd: /home/ssdrive/agent1/_work/build/1d6ffba4b3cd8b528ee7a99e3bf162a879774a1546f914315526215f77afdc11
using source provider: tfsversioncontrol
loading: /home/ssdrive/agent1/agent/scm/tfsversioncontrol
Using auth scheme: OAuth
workspace name: ws_1d6ffba4
getting code
Creating workspace ws_1d6ffba4
/home/ssdrive/TEE-CLC-14.0.1/tf arg: workspace
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-new"
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-permission:Private"
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-location:local"
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "ws_1d6ffba4"
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-collection:http://ets-tfs:8080/tfs/DriveMateCollection/"
/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-login:OAuth,******************"
exec tool: /home/ssdrive/TEE-CLC-14.0.1/tf
Arguments:
workspace
-new
-permission:Private
-location:local
ws_1d6ffba4
-collection:http://ets-tfs:8080/tfs/DriveMateCollection/
-login:OAuth,******************
An error occurred: Access denied connecting to TFS server http://ets-tfs:8080/ (authenticating as OAuth)
rc:100
success:false
/home/ssdrive/TEE-CLC-14.0.1/tf failed with return code: 100

**Comment by bryanmacfarlane** [comment]
assigning to Yang.

my guess is the issue is on-prem.  Does it work against an azure account?

on-prem is gated by ntlm even though the OAuth token will work.  With tf on windows, it uses integrated auth to on-prem so it gets through the front gate and the app respects the oauth token.

**Comment by yacaovsnc** [comment]
I've added a capability to override the oauth token credential.  

If "VSO_TFVC_USERNAME" and "VSO_TFVC_PASSWORD" are set in the environment, the agent will use this credential to connect to TFS server instead.

**Comment by bryanmacfarlane** [comment]
I'm going to also add changes where there's a special variable you can set on the definition's variables tab (along with the lock) so you don't have to go to the agent to set envvars.  That will come soon.

**Comment by bryanmacfarlane** [comment]
Also note that his changes are in master.  I need to do an npm release soon.

**Comment by bbusacker** [comment]
No problem.  I am running the master version now anyway.  I will update and rebuild when necessary.

**Comment by bbusacker** [comment]
So I'm now getting the source but the build fails with the following error:

2015-08-26T13:02:47.791Z: cd /home/ssdrive/agent1/_work/build/1d6ffba4b3cd8b528ee7a99e3bf162a879774a1546f914315526215f77afdc11/repo/$/DriveMate3/DriveMate/Branches/Brandon/NVMe2
2015-08-26T13:02:47.792Z: Getting files for $/DriveMate3/DriveMate/Branches/Brandon/NVMe2
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: get
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "."
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-recursive"
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-version:C4808"
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-noprompt"
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-collection:http://ets-tfs:8080/tfs/DriveMateCollection/"
2015-08-26T13:02:47.792Z: [debug]/home/ssdrive/TEE-CLC-14.0.1/tf arg: "-login:umtfsservice,******************"
2015-08-26T13:02:47.793Z: [debug]exec tool: /home/ssdrive/TEE-CLC-14.0.1/tf
2015-08-26T13:02:47.793Z: [debug]Arguments:
2015-08-26T13:02:47.793Z: [debug]   get
2015-08-26T13:02:47.793Z: [debug]   .
2015-08-26T13:02:47.793Z: [debug]   -recursive
2015-08-26T13:02:47.793Z: [debug]   -version:C4808
2015-08-26T13:02:47.793Z: [debug]   -noprompt
2015-08-26T13:02:47.793Z: [debug]   -collection:http://ets-tfs:8080/tfs/DriveMateCollection/
2015-08-26T13:02:47.793Z: [debug]   -login:umtfsservice,******************
2015-08-26T13:02:49.772Z: An error occurred: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2015-08-26T13:02:49.772Z: 
2015-08-26T13:02:51.820Z: [debug]rc:100
2015-08-26T13:02:51.820Z: [debug]success:false
##[Error] 2015-08-26T13:02:51.823Z: /home/ssdrive/TEE-CLC-14.0.1/tf failed with return code: 100

Where is the huge folder name coming from after _work/build?   
It also appears to also append the TFSVC path where the code is located after repo as well.

Let me know if there is anything I can do to resolve this on my end.  I'm using the shell script build step.  Thanks for your support.

**Comment by yacaovsnc** [comment]
Unfortunately this is a limitation for now and I am working on shorten the path.

**Comment by dky** [comment]
Hello, I'm experiencing the same issue:

******************************************************************************
Preparing tasks
******************************************************************************
******************************************************************************
Running prepareWorkspace
******************************************************************************
preparing Workspace
cwd: /home/dky/agent1/_work/build/f46f54f94f89b934bedae75c7737979552766fcbfc8c0beb8c13e80c4a9fce51
using source provider: tfsgit
loading: /home/dky/agent1/agent/scm/tfsgit
Using auth scheme: OAuth
running clean
getting code
https://tfs/Example/IT/_git/IT.Infrastructure.Unix.Build.Test
srcVersion: 9b5c05569a30580a827ca7d58d23c7a1f15c2328
srcBranch: refs/heads/master
Using ref: 9b5c05569a30580a827ca7d58d23c7a1f15c2328
Cloning into 'repo'...

fatal: Authentication failed for 'https://OAuth:superloghashhhhh..

/usr/bin/git failed with return code: 128

Do we know what the issue is with this? I do not want to hack up and manually provide user credentials.

**Comment by yacaovsnc** [comment]
You are running git instead of tfvc, take a look at this issue:
https://github.com/Microsoft/vso-agent/issues/68

**Comment by bbusacker** [comment]
@yacaovsnc Is the path shortening work that was merged to master complete?   Wanted to test it out if it is.

**Comment by bryanmacfarlane** [comment]
Half of it is.  We find the common root.  The work to get rid of the hash is underway.

**Comment by dky** [comment]
@yacaovsnc it appears to be git to me with some type of oauth credential? By setting:

VSO_GIT_USERNAME
VSO_GIT_PASSWORD

we are just telling it to use NTLM credentials. Should oauth work or is this expected for on-prem. We are trying to not need to hard code ENV variables.

**Comment by bryanmacfarlane** [comment]
Let's dicsuss the git creds on the other issue.

**Comment by dky** [comment]
VSO_GIT_USERNAME=buildacct
VSO_GIT_PASSWORD=some_somepassword

Worked. Restarted the agent and now my projects build.

**Comment by haxu** [comment]
I am facing this issue for few days. any good new?

**Comment by dky** [comment]
@haxu did you set the variables above? Once I set them and restarted the agent the pulls from git worked. You also should make sure the user has access/permissions to the git repositories.

**Comment by couven92** [comment]
Problem with setting the environment variables is that the authentication is now displayed in plaintext in the Build Agent management pages on the server. This might be a security risk when multiple users may manage agents

**Comment by dky** [comment]
I believe they are working to make this is as a parameter within the build web ui.

**Comment by bryanmacfarlane** [comment]
That's correct.

@couven92 - we have a filter set for vars that aren't registered as capabilities.  That's a good catch and I will fix it right now.

**Comment by bbusacker** [comment]
Creating workspace ws_1_68
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: workspace
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "-new"
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "-permission:Private"
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "-location:local"
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "ws_1_68"
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "-collection:http://ets-tfs:8080/tfs/DriveMateCollection/"
/home/ssdrive/bin/TEE-CLC-14.0.1/tf arg: "-login:bbusacker@winntdom,******************"
exec tool: /home/ssdrive/bin/TEE-CLC-14.0.1/tf
Arguments:
workspace
-new
-permission:Private
-location:local
ws_1_68
-collection:http://ets-tfs:8080/tfs/DriveMateCollection/
-login:bbusacker@winntdom,******************
An error occurred: Access denied connecting to TFS server http://ets-tfs:8080/ (authenticating as bbusacker@winntdom)
rc:100
success:false
/home/ssdrive/bin/TEE-CLC-14.0.1/tf failed with return code: 100

Trying with preview I can no longer authenticate using VSO_TFVC_USERNAME and VSO_TFVC_PASSWORD.

**Comment by bbusacker** [comment]
I can run tf successfully with these parameters manually and create a workspace but when run inside the vsoagent if fails.

**Comment by yacaovsnc** [comment]
@bbusacker did you modify the log you posted?  In the previous "successful" logins, your log shows: 2015-08-26T13:02:47.793Z: [debug] -login:umtfsservice,***************,
the latest log shows:
-login:username@domain,***************

The env variables do not appear to be set properly.

**Comment by bryanmacfarlane** [comment]
The subject of the issue (tfsvc and shorter paths) are in master.  I don't want this issue to track all TFSVC issues.  Closing this.  If there are specific issues, log more focused issues
