### ISSUE TITLE
Shellscript parameter values with whitespace

### ISSUE THREAD

**Issue by jschiessl** [Microsoft/vso-agent#77]
I have now updated one of my agents to 0.2.28 and a previously transient issue now seems to be permanent:
As part of my build definition, I am calling a shell script. This script relies on a parameter being passed down so it can then build a path where this parameter is part of the path. In my case, the parameter value contains whitespace.
Previously, most of the time the parameter got passed down like this (as can be seen in the logs)
2015-08-27T09:22:02.228Z: [command]/bin/bash /script.sh 'name parameter'

Now with 0.2.28 it seems that it gets always passed like this:
2015-08-27T09:22:02.228Z: [command]/bin/bash /script.sh name parameter

The quotes are missing, so inside the script $1 is now 'name' instead of 'name parameter', which causes significant irritation when constructing paths ;-)
This problem sometimes occured also with previous versions, but then canceling the build and queuing it again always helped.

I am passing down the parameter as $(nameparameter) in the build definition, having it defined as name parameter (without quotes) in a variable called nameparameter and receiving it in the script as $1.
Am I doing something wrong there?

**Comment by jschiessl** [comment]
So the answer for me was to define the variable with double quotes, as @bryanmacfarlane suggested. This alone led to problems with variable expansion in the path, apparently. The solution was to use double quotes again, this time in the script. Instead of building my path like
`/Users/foo/bar/$parameterwithwhitespace/somefile`
I am now doing
`/Users/foo/bar/"$parameterwithwhitespace"/somefile`

This seems to work with path expansion, even with whitespace

**Comment by bryanmacfarlane** [comment]
If you can share exactly what's in the build definition variables, what's in the inputs to the shell script task, I can make dig in to make sure it's what we expect (and perhaps clear up confusion).

Basically, inputs in tasks get replace with values from the variables tab.  Use $(var) format in the inputs for that.  Then the additional arguments input on the shellscript will respect double quotes for an argument.

**Comment by bryanmacfarlane** [comment]
I'll update help with this

**Comment by bryanmacfarlane** [comment]
should be fixed now
