### ISSUE TITLE
Ocasionally getting `No job was found with identifier...`

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vso-agent#83]
Happens once in a blue moon. Logs zip is empty. If you have access to our project, [here](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build#_a=summary&buildId=15910) are a [few](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build#_a=summary&buildId=15870) of [those](https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build#_a=summary&buildId=15803).

![image](https://cloud.githubusercontent.com/assets/22350/9651388/538ecff0-5210-11e5-8c9a-b47c01a4f107.png)

**Comment by bryanmacfarlane** [comment]
We identified it as a service side issue.  We think we understand it and will try to fix in the current or next sprint rollout.

**Comment by joaomoreno** [comment]
:+1:

**Comment by joaomoreno** [comment]
@bryanmacfarlane we're still getting these, although rarely (once every ~3 days)

**Comment by wertzui** [comment]
We are also getting this error on a regular basis:
No job was found with identifier 247.

**Comment by bryanmacfarlane** [comment]
we're investigating.  if you want to send me you account url etc... to me.  my email alias is bryanmac and that's at microsoft dot com
