### ISSUE TITLE
plain gulp invocation does not build _package

### ISSUE THREAD

**Issue by RuudHbm** [Microsoft/vso-agent#86]
After a fresh git clone, a plain gulp invocation does not build an installable npm package.

**Comment by bryanmacfarlane** [comment]
We use git + gulp + npm everyday to build our agents and tasks.  This issue has no details, no mentions of errors or any other details.  Closing

**Comment by RuudHbm** [comment]
I just followed the docs/contribute.md document on a Linux box with git, gulp and npm already installed:

lnxbld@hbmdonlnxbld01:~$ mkdir mybuild
lnxbld@hbmdonlnxbld01:~$ cd mybuild
lnxbld@hbmdonlnxbld01:~/mybuild$ git clone https://github.com/Microsoft/vso-agent.git
Cloning into 'vso-agent'...
remote: Counting objects: 3550, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 3550 (delta 7), reused 0 (delta 0), pack-reused 3519
Receiving objects: 100% (3550/3550), 1.06 MiB | 1.11 MiB/s, done.
Resolving deltas: 100% (2208/2208), done.
Checking connectivity... done.
lnxbld@hbmdonlnxbld01:~/mybuild$ ll
total 12
drwxrwxr-x  3 lnxbld lnxbld 4096 Sep  8 15:41 ./
drwxr-xr-x 35 lnxbld lnxbld 4096 Sep  8 15:40 ../
drwxrwxr-x  5 lnxbld lnxbld 4096 Sep  8 15:41 vso-agent/
lnxbld@hbmdonlnxbld01:~/mybuild$ cd vso-agent
lnxbld@hbmdonlnxbld01:~/mybuild/vso-agent$ gulp
[15:41:53] Using gulpfile ~/mybuild/vso-agent/gulpfile.js
[15:41:53] Starting 'clean'...
lnxbld@hbmdonlnxbld01:~/mybuild/vso-agent$ ll
total 48
drwxrwxr-x 5 lnxbld lnxbld 4096 Sep  8 15:41 ./
drwxrwxr-x 3 lnxbld lnxbld 4096 Sep  8 15:41 ../
drwxrwxr-x 2 lnxbld lnxbld 4096 Sep  8 15:41 docs/
drwxrwxr-x 8 lnxbld lnxbld 4096 Sep  8 15:41 .git/
-rw-rw-r-- 1 lnxbld lnxbld 3086 Sep  8 15:41 .gitattributes
-rw-rw-r-- 1 lnxbld lnxbld  399 Sep  8 15:41 .gitignore
-rw-rw-r-- 1 lnxbld lnxbld 3005 Sep  8 15:41 gulpfile.js
-rw-rw-r-- 1 lnxbld lnxbld 1086 Sep  8 15:41 LICENSE.txt
-rw-rw-r-- 1 lnxbld lnxbld 1500 Sep  8 15:41 package.json
-rw-rw-r-- 1 lnxbld lnxbld 3745 Sep  8 15:41 README.md
-rw-rw-r-- 1 lnxbld lnxbld  895 Sep  8 15:41 sources
drwxrwxr-x 6 lnxbld lnxbld 4096 Sep  8 15:41 src/
lnxbld@hbmdonlnxbld01:~/mybuild/vso-agent$ 

Nothing has been built: no _package which can be installed with npm ...

**Comment by bryanmacfarlane** [comment]
In your steps above I don't see this step from the docs ...

Install remaining pre-reqs and gulp tasks (run from root of repo)

sudo npm install

As a side note, I don't think that step needs sudo
