### ISSUE TITLE
on-prem TFS - Unauthorized(401) ... /tfs/_apis/connectionData

### ISSUE THREAD

**Issue by LairdWilliams** [Microsoft/vso-agent#87]
Am attempting to put xplat agent on a mac mini running OS X Yosemite (Server) against an on-prem install of TFS 2015 (release, no RC or RTM).

$ node -v && npm -v
v0.12.7
2.11.3

I have basic auth turned on for the TFS site to which I am connecting.
The mac mini is not joined to the AD domain that is hosting TFS - but TFS, DB, and SharePoint servers involved are.

Here is a redacted transcript of my attempt to configure the agent on first run:

$ node agent/vsoagent
Enter alternate username > tfsBuild
Enter alternate password > 
Enter server url > http://myTFS:8080/tfs
Enter agent name (enter sets OSXBox)  > 
Enter agent pool name (enter sets default)  > 
Error starting the agent
Failed Request: Unauthorized(401) - http://myTFS:8080/tfs/_apis/connectionData

Here is the funny thing. If I fire up Safari (or even Edge on my Win10 workstation) and plunk the above "unauthorized" URL into the address bar, I will get the prompt for login. If I then enter the exact same service account credentials used above, I get back a nice json response...no 401 error. So, clearly, the basic auth is working and the service account has all the permissions it needs to get past this point. Any thoughts on what is special about the agent "builder" ?

Experiments I have already done:
1) Use my own (Site Collection and everything else admin) creds - same behavior.
2) Turn off ALL other forms of authentication on the IIS server for TFS and restart the server - same behavior.
3) Fired up Xcode the the mac in question, connected to TFS, pulled main from an app and built it from within Xcode using the tfsBuild credentials for connecting to TFS - success.
4) Pitched ALL of the cached passwords in the mac keychain related to my TFS server - no change.

**Comment by milliamp** [comment]
I very recently configured a similar set up. After struggling through many many combinations, I found that the alternate username needed to be in the following format: "<username>@<AD FQDN>". This was with Basic Auth turned on for TFS.
If possible give that a go.

**Comment by bryanmacfarlane** [comment]
Instructions are here

https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md

**Comment by LairdWilliams** [comment]
milliamp - thanks for the ping. I will give that credentials syntax a shot.

Bryan - thanks also. While I have been trying both [user] and [domain]\[user] for the username, I had NOT left the domain/realm blank in the basic auth setup. I will strip out what is there and give that a shot too. That link is fantastic. Again, though - what is weird to me is how I can get the URL in question using the same creds from the browser with no issue. Clearly there is some subtlety that I don't fully understand at work here - which comes as no big surprise.

**Comment by LairdWilliams** [comment]
So the key was to keep the domain/realm blank on the configuration for the basic auth. I can have basic auth and windows auth both active. I can also use either [domain]\[userid] or [userid]@[domain] and it works.

Now I have to work out why the agent is not being allowed to get the code from the TFS git repo. That is a different issue though - this one can go. I DO encourage linking that very helpful post from the main page here. I'm not sure how many folks would think to look in the tbs-cli project for instructions that are also relevant to this project. THX all.
