### ISSUE TITLE
Add helper to vso-task-lib to access the WebApi from vso-agent in a Build Task

### ISSUE THREAD

**Issue by milliamp** [Microsoft/vso-agent#89]
I would like to connect to a TFS API from a build task. vso-node-api provides a method for the call I want to make and I can make the call if I explicitly require vso-node-api in my task and pass it a new authentication handler, with username and password for the TFS server.

There are clearly better way to do this but I can't figure out the best way. I can see that the PublishBuildArtifacts task uses "tl.command("artifact.upload", data, "Uploading artifact");" but I can't find a reference for how 'commands' line up with the WebApis.

Alternatively, is there a way to connect to use a token from the vso-agent itself to get the WebApi or connection to the TFS Server?

ps. the call from vso-node-api I am making is "buildApi.getBuildCommits(project, build, callback)"

Any direction or help would be wonderful.

**Comment by bryanmacfarlane** [comment]
I need to add vso-node-api to vso-task-lib and offer a method to hand over the webapi with the token already set (server sends in message to agent, agent node handler needs to set and vso-task-lib needs to read).

I'll leave this open and implement soon.

**Comment by bryanmacfarlane** [comment]
Also as an FYI - tl.commands uses a way to write back to the server via a stdout command.  How that works is you can write certain things to stdout via ##vso[...]...  and the agent will intercept and do work on your behalf since it has the token.  Also useful from shell/cmd scripts.  However, only useful for writebacks - not for querying.  You need the api for that. 

https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md

**Comment by milliamp** [comment]
Cheers for that Bryan. Excellent answer.

**Comment by gravufo** [comment]
Any news on this? I need to create a custom task that customizes the build number and I need to have access to the previous build number. It can be done through the REST API, but I don't want to have to authenticate using a username and password hardcoded in the source code...Using the already-authenticated agent to run the rest call would fix this issue and be ideal!

Thanks

**Comment by bryanmacfarlane** [comment]
@gravufo can you log this issue in the vsts-task-lib repo?  This agent is being deprecated for new agent.  I'm in the process of implementing getwebapi in task lib

new agent: https://github.com/Microsoft/vsts-agent

**Comment by gravufo** [comment]
Sure! Done. For reference purpose, here's the link: [Issue 71](https://github.com/Microsoft/vsts-task-lib/issues/71).

Looking forward to the new agent :)
