### ISSUE TITLE
Agent doesn't store configured username/password on first run

### ISSUE THREAD

**Issue by mrquantize** [Microsoft/vso-agent#92]
Hi, according to the documentation, the agent should only ask for a username/password the first time it is run, and save this information for future runs. In the example output from running `node agent/vsoagent`, there is a line that says `Config saved`. However I don't see this - I am prompted for the username/password every time. This means I cannot run the agent as a service.

Am I missing something?

Running Ubuntu 15.04

**Comment by mrquantize** [comment]
OK, I notice now that if I supply `-u` and `-p` arguments for username/password when starting the agent, this enables it to log in unattended. But it would be preferable if this information was stored securely somewhere rather than having to be passed in plain text.

**Comment by bryanmacfarlane** [comment]
Yes, there's an issue tracking to use key chain

**Comment by bryanmacfarlane** [comment]
For Linux we will offer Docker and/or stored creds as well
