### ISSUE TITLE
Detecting a build is running on vso agent

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vso-agent#97]
I'm following this article here and I'm getting an issue with this which suggest the build conditions are no longer valid for VSO in order to detect it's running on VSO.

http://blogs.msdn.com/b/davidhardin/archive/2013/01/18/building-and-packaging-virtual-applications-within-azure-projects.aspx

Is it possible to detect that a build is running in VSO in a way I can modify the work in the article to make sure the logic works ?

**Comment by bryanmacfarlane** [comment]
I don't think this is an issue or related to the Linux/OSX xplat node agent
